// RLR · Go-to-market de Video Room: las tareas del checklist.
// Cada tarea: id (NO cambiarlo: es la llave de lo ya palomeado), fase (1–5),
// área, quién la hace, esfuerzo, ritmo, título y detalle (qué es, por qué y
// cuándo se da por hecha). Para agregar una tarea: una línea con id nuevo.
//
//  área:     MKT marketing · CON contenido · VEN ventas · ALI alianzas ·
//            PRO producto · ADM administración · DAT datos
//  quién:    P persona · IA inteligencia artificial · A ambas (la IA prepara, la persona ejecuta)
//  esfuerzo: 1 = media hora · 2 = unas horas · 3 = un día · 4 = varios días
//  ritmo:    u una vez · d diario · s semanal · m mensual
export type Tarea = [id: string, fase: number, area: string, quien: string, esfuerzo: number, ritmo: string, titulo: string, detalle: string];

export const TAREAS: Tarea[] = [
  // ── Fase 1 · Cimientos ────────────────────────────────────────────────
  ["101", 1, "ADM", "A", 2, "u", "Escribir y publicar la política de contenido", "Qué no se permite: contenido para adultos, apuestas, diagnósticos médicos, promesas de dinero o de salud. Stripe cierra cuentas por esto y sin cuenta de cobros no hay empresa. Hecho cuando está enlazada en el pie y en el FAQ."],
  ["102", 1, "ADM", "P", 4, "u", "Términos de uso y aviso de privacidad revisados por abogado", "Que cubran quién responde por el contenido, que nada se graba y cómo se manejan saldos y disputas. Hecho cuando el abogado firma la versión publicada."],
  ["103", 1, "ADM", "P", 3, "u", "Confirmar con un fiscalista el régimen de plataformas", "La pregunta exacta: ¿Video Room debe retener impuestos a los creadores como plataforma de intermediación? Resolver antes de la fase 3. Hecho con respuesta por escrito y plan."],
  ["104", 1, "ADM", "P", 3, "u", "Revisar con abogado la figura del monedero", "El saldo se recarga, se manda entre personas y lo ganado se retira. Confirmar que la estructura actual no pide una autorización especial. Hecho con opinión por escrito."],
  ["105", 1, "ADM", "P", 3, "u", "Abrir el Stripe propio y cambiar el cobro", "Hoy se cobra con la cuenta de SuperLeads. Dar de alta la de CapitalTorreon, ligar el secreto y el aviso de pagos. Hecho cuando una recarga real cae en la cuenta nueva."],
  ["106", 1, "ADM", "P", 2, "u", "Anotar la comisión real de tarjeta y de retiro", "Pedir a Stripe por escrito el costo de tarjeta nacional, extranjera, impuestos y retiro. Ponerlos en la pestaña Números. Hecho cuando la calculadora usa los números reales."],
  ["107", 1, "PRO", "A", 2, "u", "Decidir la recarga mínima y la sugerida", "Con $50 la tarjeta se lleva cerca del 11 %; con $200, cerca del 6 %. Subir el mínimo o resaltar $200. Hecho cuando la recarga promedio pasa de $150."],
  ["108", 1, "ADM", "A", 2, "u", "Límites contra fraude para cuentas nuevas", "Tope de recarga diaria, espera de 72 horas en el primer retiro y una regla clara ante contracargos. Hecho cuando está escrito y programado."],
  ["109", 1, "ADM", "P", 1, "u", "Correo y WhatsApp de soporte con promesa de tiempo", "Un solo correo y un solo número, con respuesta en menos de 4 horas hábiles. Hecho cuando aparece en el pie del sitio y en los correos."],
  ["110", 1, "ADM", "P", 2, "u", "Registrar la marca Video Room", "En el IMPI, clases 38, 41 y 42. Es barato y evita que alguien la tome cuando crezca. Hecho con el folio de solicitud."],
  ["111", 1, "ADM", "P", 2, "s", "Conciliación semanal de dinero", "Lo que entró por Stripe contra los saldos de usuarios y lo que se debe a creadores. Hecho cuando hay una hoja que cuadra cada lunes."],
  ["112", 1, "DAT", "IA", 3, "u", "Tablero semanal con seis números", "Creadores que cobraron, puerta total, sesiones pagadas, registros, porcentaje que transmite en 7 días y porcentaje que repite a 30. Hecho cuando llega solo cada lunes."],
  ["113", 1, "DAT", "IA", 2, "u", "Medir el «primer peso»", "Por cada creador, los días desde que creó su sala hasta su primera entrada pagada. Dice qué tan bien arrancan. Hecho cuando sale en el tablero."],
  ["114", 1, "DAT", "IA", 2, "u", "Reporte de registros por fuente", "Ya se guarda de dónde llegó cada registro; falta verlo por semana y por red. Hecho cuando sabes qué red trae creadores que sí cobran."],
  ["115", 1, "DAT", "IA", 2, "u", "Medir cuántos espectadores se vuelven creadores", "Es el circuito que lleva de 100 a 1,000 sin pagar anuncios. Hecho cuando el tablero dice cuántos creadores nuevos habían entrado antes a ver."],
  ["116", 1, "DAT", "IA", 1, "u", "Aviso diario al equipo", "Un mensaje cada noche: hoy cobraron tantos creadores y tanto de puerta. Mantiene el pulso. Hecho cuando llega siete días seguidos."],
  ["117", 1, "PRO", "IA", 3, "u", "Cinco páginas por tipo de creador", "Expertos, lecturas, músicos, clases y maestros, cada una con su titular, un ejemplo de precio y el botón de crear sala. Hecho cuando cada mensaje directo puede llevar a su página."],
  ["118", 1, "CON", "A", 2, "u", "Demostración de 60 segundos", "De «crear sala» a «entró el primer pago», grabada en un teléfono real. Es el archivo que más se va a mandar. Hecho cuando está fijada en todos los perfiles."],
  ["119", 1, "VEN", "P", 1, "s", "Sala de demostración con horario fijo", "Una sala de la casa donde alguien recibe a los curiosos, por ejemplo martes y jueves a las 7 pm. Hecho cuando el horario está en la página de inicio."],
  ["120", 1, "PRO", "IA", 2, "u", "Calculadora pública «¿cuánto ganarías?»", "Personas por precio por sesiones al mes, con lo que se queda el creador. Convierte curiosos. Hecho cuando está en la página de inicio."],
  ["121", 1, "PRO", "IA", 2, "u", "Tres mensajes de arranque al crear sala", "Día 0: tu link y tus diseños. Día 1: tu plan de primera sesión. Día 3: ¿te ayudamos a montarla? Hecho cuando salen solos."],
  ["122", 1, "PRO", "IA", 2, "u", "Cinco correos para quien no ha transmitido", "Un caso, un truco y una objeción resuelta por correo, durante dos semanas. Hecho cuando se apagan solos al transmitir."],
  ["123", 1, "PRO", "P", 3, "u", "Ver a cinco personas usar el producto por primera vez", "Tres en iPhone y dos en Android, sin ayudarles y grabando la pantalla. Hecho con la lista de dónde se atoraron."],
  ["124", 1, "PRO", "A", 3, "u", "Prueba con 100 personas en una sala", "Antes de un evento grande hay que saber que aguanta. Hecho cuando una sala con 100 entradas corre una hora sin cortes."],
  ["125", 1, "PRO", "IA", 3, "u", "Tarjeta «mis primeros pesos» lista para compartir", "Al cobrar por primera vez se genera una imagen con el monto y su link. Es el anuncio más creíble que existe. Hecho cuando se ofrece sola al terminar."],
  ["126", 1, "MKT", "A", 1, "u", "Fijar el mensaje único", "«El en vivo gratis es el anuncio. La sala es el negocio.» y tres pruebas: nada se graba, llega completo, el link es tuyo. Hecho cuando todo el equipo lo dice igual."],
  ["127", 1, "MKT", "P", 2, "u", "Apartar el nombre en todas las redes", "TikTok, Instagram, Facebook, YouTube, X y WhatsApp Business, con el mismo nombre de usuario. Hecho cuando las seis existen."],
  ["128", 1, "MKT", "A", 1, "u", "Perfil idéntico en todas las redes", "Misma foto, misma frase y el link con su etiqueta de origen. Los diseños ya están en Materiales. Hecho cuando se ven iguales."],
  ["129", 1, "MKT", "P", 1, "u", "Canal de WhatsApp para creadores", "Un canal de difusión para novedades y casos. Hecho cuando tiene sus primeros 50 seguidores."],
  ["130", 1, "VEN", "A", 1, "u", "WhatsApp Business con respuestas rápidas", "Cargar las respuestas de Materiales: cómo entro, se graba, cuánto cuesta. Hecho cuando contestar toma dos toques."],
  ["131", 1, "MKT", "IA", 2, "u", "Carpeta de prensa", "Una página con qué es, por qué importa, datos, fotos del fundador y logotipos. Hecho cuando un periodista puede escribir la nota sin llamarte."],
  ["132", 1, "VEN", "IA", 2, "u", "Las 30 objeciones y su respuesta", "«¿Y si no entra nadie?», «¿por qué no Zoom?», «¿es seguro?». Hecho cuando el equipo las tiene a un toque."],
  ["133", 1, "MKT", "IA", 2, "u", "Comparación honesta con las alternativas", "Contra TikTok LIVE, Zoom con transferencia y membresías de YouTube: qué se queda cada quien y qué se graba. Hecho cuando está publicada."],
  ["134", 1, "VEN", "P", 2, "u", "Tablero de creadores en el CRM", "Etapas: detectado, contactado, respondió, sala creada, primera sesión, primer peso, repite. Hecho cuando cada creador vive en una tarjeta."],
  ["135", 1, "VEN", "IA", 2, "u", "Mensajes directos en tres versiones por tipo", "Corto, con dato y con video, para cada uno de los cinco tipos de creador. Hecho con 15 mensajes listos para copiar."],
  ["136", 1, "VEN", "IA", 1, "u", "Guion de llamada de 10 minutos", "Para montar la primera sesión: fecha, precio, tres anuncios y la frase de cierre. Hecho cuando cualquiera puede darla."],
  ["137", 1, "VEN", "P", 1, "u", "Oferta de arranque: «tu primera sesión la montamos nosotros»", "Le hacemos sus diseños y su anuncio, y lo acompañamos en vivo. Quita el miedo. Hecho cuando está escrita en una hoja."],
  ["138", 1, "VEN", "P", 2, "u", "Garantía de primera sesión", "Si anuncia tres veces y gana menos de $300, la casa pone la diferencia. Tope de 50 creadores. Hecho con las reglas escritas y el dinero apartado."],
  ["139", 1, "VEN", "A", 3, "u", "Lista de 300 creadores objetivo", "Cien por cada tipo a probar, con seguidores, cada cuánto transmiten y cómo contactarlos. Hecho cuando está en el CRM."],
  ["140", 1, "VEN", "IA", 1, "u", "Plan de primera sesión en una hoja", "Fecha, precio, tres publicaciones y la frase de cierre. Se le manda al creador al crear su sala. Hecho cuando existe la plantilla."],
  ["141", 1, "MKT", "IA", 2, "u", "Página «cómo funciona el dinero»", "Transparencia total: 4 de cada 5 pesos de la puerta, lo que mandan llega completo y el retiro no tiene comisión de la casa. Hecho cuando está enlazada desde el inicio."],
  ["142", 1, "PRO", "IA", 2, "u", "Botón «reportar esta sala»", "Un reporte que llega al correo de la casa con la sala y el motivo. Hecho cuando un reporte de prueba llega."],
  ["143", 1, "ADM", "P", 2, "u", "Presupuesto de los primeros tres meses", "Cuánto para la persona, el editor, la garantía y las herramientas. Hecho cuando hay un tope mensual escrito."],
  ["144", 1, "DAT", "IA", 2, "u", "Definir qué es un creador activo", "Propuesta: cobró al menos una entrada en los últimos 30 días. Todo el plan se mide con esa regla. Hecho cuando el tablero la usa."],

  // ── Fase 2 · Los primeros 10, a mano ──────────────────────────────────
  ["201", 2, "VEN", "P", 3, "u", "El fundador transmite primero: tres sesiones cobradas", "Con tu propio tema y tu propia gente. No se puede vender lo que no se ha vivido. Hecho con tres sesiones y tus notas de cada una."],
  ["202", 2, "VEN", "P", 2, "u", "Veinte invitaciones personales por audio", "A conocidos con público: un músico, un contador, una maestra, un entrenador. Audio de WhatsApp, no texto. Hecho con 20 audios enviados."],
  ["203", 2, "VEN", "P", 3, "u", "Tres expertos que contestan casos", "Pensiones, impuestos o migración: ya hacen en vivos gratis contestando dudas. Hecho cuando los tres tienen fecha."],
  ["204", 2, "VEN", "P", 3, "u", "Tres personas de lecturas y guía", "Tarot, astrología o numerología, con en vivos diarios en TikTok. Hecho cuando los tres tienen fecha."],
  ["205", 2, "VEN", "P", 3, "u", "Tres músicos o comediantes", "Cantautores, tríos, DJs o comediantes con público local. Hecho cuando los tres tienen fecha."],
  ["206", 2, "VEN", "P", 2, "u", "Un instructor y un maestro como comparación", "Zumba o yoga, e idiomas o regularización. Sirven para comparar contra los tres tipos principales. Hecho con dos fechas más."],
  ["207", 2, "VEN", "P", 2, "u", "Llamada de montaje con cada uno", "Diez minutos: fecha, precio, tres anuncios y frase de cierre. Hecho cuando los diez tienen su hoja de plan."],
  ["208", 2, "VEN", "A", 2, "u", "Sus diseños hechos por nosotros", "Con Materiales: el anuncio, los horarios y «estoy en vivo», con su nombre y su QR. Hecho cuando cada uno recibe su carpeta."],
  ["209", 2, "VEN", "P", 3, "u", "Acompañar en vivo la primera sesión de cada uno", "Estar en la sala y en WhatsApp durante su primera hora. Hecho en las diez primeras sesiones."],
  ["210", 2, "VEN", "P", 1, "u", "Tres preguntas después de cada sesión", "¿Qué te gustó? ¿Qué estorbó? ¿Qué dijo tu gente? Hecho cuando hay respuestas de los diez."],
  ["211", 2, "CON", "P", 2, "u", "Testimonio en video de 30 segundos", "De cada creador que cobró, grabado con su teléfono. Hecho con al menos cinco videos."],
  ["212", 2, "CON", "P", 1, "u", "Permiso para enseñar su número", "La captura de lo que ganó en su primera hora, con autorización por escrito. Hecho con cinco permisos."],
  ["213", 2, "VEN", "P", 1, "u", "Segunda sesión agendada antes de colgar", "La repetición es lo que hace negocio. Hecho cuando al menos seis de diez tienen segunda fecha."],
  ["214", 2, "VEN", "A", 1, "u", "Enseñar «el after» con su frase exacta", "La frase para cerrar su en vivo gratis y pasar a la sala, escrita para cada uno. Hecho cuando la usan al menos cinco."],
  ["215", 2, "PRO", "P", 2, "u", "Bitácora de tropiezos", "Cada cosa que estorbó en las primeras diez sesiones, ordenada por cuántas veces pasó. Hecho con la lista priorizada."],
  ["216", 2, "PRO", "IA", 4, "u", "Arreglar los cinco tropiezos más repetidos", "Antes de invitar a cien hay que quitar lo que hizo tropezar a diez. Hecho cuando los cinco están resueltos."],
  ["217", 2, "PRO", "P", 2, "u", "Ver una sesión desde un teléfono modesto con datos", "Así entra la mayoría del público. Hecho cuando el video y el chat se sostienen."],
  ["218", 2, "PRO", "P", 1, "u", "Revisar recibos y correos reales", "Que a cada parte le llegó su recibo con el monto y la hora correctos. Hecho en las diez sesiones."],
  ["219", 2, "PRO", "P", 2, "u", "Tres retiros reales a banco", "Es el momento en que el creador cree. Hecho cuando tres creadores confirman que el dinero llegó."],
  ["220", 2, "CON", "A", 2, "u", "Primer caso escrito con número real", "«Cuánto ganó Fulana en su primera hora»: quién es, qué hizo, cuánto y cómo. Hecho cuando está publicado."],
  ["221", 2, "CON", "A", 2, "u", "Un video corto por cada caso", "De 30 a 45 segundos: gancho, número y cómo lo hizo. Hecho con tres videos publicados."],
  ["222", 2, "CON", "P", 1, "d", "Un video diario desde el día uno", "Aunque no haya casos todavía: construir en público. La constancia vale más que la producción. Hecho con 14 días seguidos."],
  ["223", 2, "CON", "IA", 2, "u", "Diez guiones de «el after» por tipo de creador", "Cincuenta guiones cortos listos para grabar. Hecho cuando están en una carpeta compartida."],
  ["224", 2, "CON", "A", 2, "u", "Tutorial «tu primera sesión en 5 minutos»", "Grabado en pantalla, sin cortes. Hecho cuando está en YouTube y en la bienvenida."],
  ["225", 2, "MKT", "IA", 2, "u", "Página de casos", "Los tres primeros casos con foto, número y video. Hecho cuando está enlazada desde el inicio."],
  ["226", 2, "VEN", "P", 2, "s", "Sala de bienvenida semanal", "«Cómo cobrar tu primer en vivo», dentro de Video Room y gratis. Vendemos usando el producto. Hecho con dos ediciones."],
  ["227", 2, "MKT", "A", 1, "u", "Primer boletín a los registrados", "Un caso, un truco y la fecha de la sala de bienvenida. Hecho cuando sale el primero."],
  ["228", 2, "DAT", "IA", 2, "u", "Tabla de la prueba de tipos", "Por creador: lo que generó en 14 días, cuánta gente entró y si repitió. Hecho cuando se ve en una sola pantalla."],
  ["229", 2, "DAT", "A", 1, "u", "Elegir con datos el tipo principal y el secundario", "Regla: más dinero por creador multiplicado por el porcentaje que repite. Hecho con la decisión escrita y fechada."],
  ["230", 2, "ADM", "P", 1, "u", "Pagar la garantía a quien aplique", "Y anotar cuánto costó activar a cada creador. Hecho cuando la cuenta está cerrada."],
  ["231", 2, "ADM", "P", 1, "s", "Hoja «lo que aprendimos»", "Una página por semana: qué funcionó, qué no y qué cambia. Hecho con tres semanas escritas."],
  ["232", 2, "VEN", "P", 1, "u", "Grupo de WhatsApp de los primeros diez", "Para que se cuenten entre ellos cómo les fue. Los primeros son los que más enseñan. Hecho cuando conversan solos."],

  // ── Fase 3 · Los primeros 100 ─────────────────────────────────────────
  ["301", 3, "ADM", "P", 1, "u", "Publicar la vacante de líder de creadores", "El texto está en la pestaña Equipo. Buscar en agencias de TikTok LIVE, comunidades de streamers y ventas por mensaje. Hecho con 20 candidatos."],
  ["302", 3, "ADM", "P", 3, "u", "Prueba pagada de siete días a tres finalistas", "La misma meta para los tres: lograr que tres creadores cobren su primera sesión. Hecho cuando hay un ganador claro."],
  ["303", 3, "ADM", "P", 2, "u", "Contratar y entregar las herramientas", "Tablero, CRM, esta página y Materiales. Hecho cuando en su primer día ya manda mensajes."],
  ["304", 3, "ADM", "P", 1, "u", "Contratar un editor de video corto por pieza", "Pago por video entregado, tres al día. Hecho con una semana de prueba."],
  ["305", 3, "ADM", "P", 1, "s", "Reunión semanal de 30 minutos", "Los seis números, tres aprendizajes y tres apuestas para la semana. Hecho cuando se cumple cuatro semanas seguidas."],
  ["306", 3, "ADM", "P", 2, "u", "Manual de soporte", "Qué hacer con un retiro atorado, un contracargo o una disputa entre creador y espectador. Hecho cuando alguien nuevo puede resolverlo."],
  ["307", 3, "ADM", "P", 1, "s", "Revisión semanal de salas reportadas", "Aplicar la política de contenido sin excepciones. Hecho cuando cada reporte tiene respuesta en 24 horas."],
  ["308", 3, "ADM", "P", 2, "u", "Acuerdo simple para embajadores", "Una hoja: qué hacen, cuánto ganan y cuándo se paga. Hecho cuando el abogado la aprueba."],
  ["309", 3, "VEN", "P", 3, "d", "Cuarenta mensajes directos al día", "Al tipo de creador ganador. Meta mensual: 880 mensajes, 70 respuestas, 26 salas y 13 con primer peso. Hecho cuando el ritmo dura dos semanas."],
  ["310", 3, "VEN", "P", 2, "d", "Diez comentarios útiles al día", "En en vivos y publicaciones de creadores objetivo. Aportar, no vender: así contestan los mensajes. Hecho con dos semanas seguidas."],
  ["311", 3, "VEN", "P", 1, "d", "Seguimiento a las 48 horas y a los 7 días", "Dos toques y ya. Insistir más quema el nombre. Hecho cuando el CRM lo recuerda solo."],
  ["312", 3, "VEN", "P", 2, "s", "Dos salas de bienvenida por semana", "Martes y jueves a las 7 pm. Ahí se resuelven dudas y se agenda la primera sesión. Hecho con ocho ediciones."],
  ["313", 3, "VEN", "P", 3, "s", "Montaje de primera sesión a toda sala con más de mil seguidores", "Llamada, plan y diseños. Es donde más rinde el tiempo. Hecho cuando ninguna se queda sin llamada."],
  ["314", 3, "VEN", "P", 2, "s", "Trato directo del fundador a creadores grandes", "Arriba de 50 mil seguidores escribe Ricardo. Hecho con diez conversaciones abiertas."],
  ["315", 3, "VEN", "A", 1, "s", "Rescatar a quien creó sala y no transmitió", "Un mensaje al tercer día con una fecha propuesta. Hecho cuando todos reciben el toque."],
  ["316", 3, "VEN", "P", 2, "s", "Rescatar a quien transmitió sin público", "Plan de tres anuncios y segunda fecha. La primera sala vacía no debe ser la última. Hecho cuando todos tienen segunda fecha."],
  ["317", 3, "VEN", "A", 3, "u", "Reto de 30 días: cuatro sesiones, tus primeros $1,000", "Un programa con fechas, grupo y tabla de avance. Hecho con la primera generación de 30 creadores."],
  ["318", 3, "VEN", "P", 1, "s", "Grupo de WhatsApp por generación", "Cada grupo de creadores que arranca junto se acompaña. Hecho cuando cada generación tiene su grupo."],
  ["319", 3, "VEN", "P", 1, "s", "Actualizar las objeciones cada viernes", "Lo que se oyó en la semana y la mejor respuesta. Hecho cuando el documento cambia cada semana."],
  ["320", 3, "VEN", "A", 2, "u", "Guía «cobra $100, no $20»", "Por qué un precio más alto atrae mejor público y cómo subirlo. Sube el promedio de todos. Hecho cuando se manda en la bienvenida."],
  ["321", 3, "VEN", "A", 2, "s", "Lunes de estreno", "Juntar a los creadores nuevos para que estrenen el mismo día: se nota en redes. Hecho con cuatro lunes."],
  ["322", 3, "VEN", "P", 1, "s", "Felicitar cada primer peso", "Un mensaje personal del equipo cuando alguien cobra por primera vez, con su tarjeta para compartir. Hecho cuando ninguno pasa sin felicitación."],
  ["323", 3, "CON", "A", 3, "d", "Tres videos cortos al día", "Un caso o dato, un tutorial y un detrás de cámaras. El mismo video va a TikTok, Reels y Shorts: 270 publicaciones al mes. Hecho con 30 días seguidos."],
  ["324", 3, "CON", "IA", 2, "u", "Banco de 100 ganchos", "Las primeras dos líneas deciden todo. Hecho con 100 ganchos ordenados por tipo de creador."],
  ["325", 3, "CON", "A", 2, "s", "Serie semanal «¿cuánto ganó?»", "Un creador, una hora, un número. Hecho con ocho capítulos."],
  ["326", 3, "CON", "A", 2, "s", "Serie «el after»", "Clips de creadores cerrando su en vivo e invitando a su sala. Enseña la jugada mejor que cualquier explicación. Hecho con ocho clips."],
  ["327", 3, "CON", "A", 3, "s", "Un video largo por semana en YouTube", "Tutorial por tipo de creador. YouTube trae búsquedas durante años. Hecho con ocho videos."],
  ["328", 3, "CON", "A", 1, "d", "Una publicación diaria en Facebook", "En la página propia: el público de expertos y de lecturas vive ahí. Hecho con 30 días seguidos."],
  ["329", 3, "CON", "P", 2, "s", "Tres aportaciones por semana en grupos", "En grupos de Facebook del tipo ganador, respondiendo dudas reales. Hecho cuando los administradores te conocen."],
  ["330", 3, "CON", "A", 1, "d", "Una publicación diaria en X", "Construir en público con números reales. Atrae prensa y gente de tecnología. Hecho con 30 días seguidos."],
  ["331", 3, "CON", "A", 2, "s", "Boletín semanal para creadores", "Un caso, un truco y una novedad. Hecho con ocho ediciones."],
  ["332", 3, "CON", "IA", 2, "m", "Diseños de temporada en Materiales", "Día de Muertos, Buen Fin, Navidad, 14 de febrero y 10 de mayo. Hecho dos semanas antes de cada fecha."],
  ["333", 3, "CON", "P", 1, "s", "Archivo de testimonios", "Todos los clips ordenados por tipo de creador para usarlos en mensajes. Hecho cuando hay 20."],
  ["334", 3, "CON", "IA", 2, "s", "Subtítulos y versión para cada red", "Cada video con texto en pantalla, en vertical y en cuadrado. Hecho cuando sale solo en el flujo."],
  ["335", 3, "CON", "A", 2, "m", "Calendario de cuatro semanas", "Qué sale cada día y quién lo hace. Hecho cuando el mes siguiente está planeado antes del día 25."],
  ["336", 3, "CON", "A", 2, "d", "Dos historias al día", "Detrás de cámaras, números del día y quién está en vivo. Hecho con 30 días seguidos."],
  ["337", 3, "MKT", "IA", 4, "u", "Veinte artículos para buscadores", "«Cómo cobrar por clases en línea», «cómo ganar dinero con TikTok LIVE en México», «alternativa a Zoom para cobrar». Hecho con 20 publicados."],
  ["338", 3, "MKT", "P", 2, "u", "Nota en prensa local", "El Siglo de Torreón y Milenio Laguna: empresa hecha en Torreón que le paga a creadores. Hecho con una nota publicada."],
  ["339", 3, "MKT", "P", 3, "u", "Cinco pódcast de creadores y negocios", "Proponerte como invitado con un dato propio. Hecho con dos grabados."],
  ["340", 3, "MKT", "P", 2, "u", "Tres aliados que enseñan a monetizar", "Cuentas que ya enseñan a ganar dinero en redes: darles acceso temprano y papel de embajador. Hecho con tres publicaciones suyas."],
  ["341", 3, "MKT", "A", 2, "u", "Recordar a quien ya nos visitó", "Anuncios mínimos, $100 al día, solo a quien visitó Materiales o creó sala sin transmitir. Hecho con dos semanas de datos."],
  ["342", 3, "MKT", "A", 2, "u", "Probar el anuncio de la garantía", "«Tu primera sesión, garantizada», con tope de $5,000. Hecho cuando sabes cuánto cuesta un creador activado."],
  ["343", 3, "MKT", "IA", 1, "u", "Testimonios en la página de inicio", "Tres caras y tres números. Hecho cuando están en la primera pantalla."],
  ["344", 3, "MKT", "IA", 2, "u", "Lanzamiento en comunidades de tecnología", "Product Hunt y foros de emprendedores, con la historia de «nada se graba». Hecho con el lanzamiento publicado."],
  ["345", 3, "MKT", "A", 2, "u", "Muro de «pagado a creadores»", "Un número en la página de inicio que crece solo. Prueba pública de que el dinero llega. Hecho cuando está en vivo."],
  ["346", 3, "PRO", "IA", 4, "u", "Programar la sesión con fecha y cuenta regresiva", "La sala muestra «empieza el sábado a las 8» y el botón Avísame. Hecho cuando un creador puede agendar."],
  ["347", 3, "PRO", "IA", 2, "u", "Recordatorio al creador 24 horas y 1 hora antes", "Con su diseño de «hoy» listo para publicar. Hecho cuando sale solo."],
  ["348", 3, "PRO", "IA", 2, "u", "Una línea al terminar: «tú también tienes una sala»", "Para quien entró a ver, sin ventanas emergentes. Es el circuito de espectador a creador. Hecho cuando aparece al final."],
  ["349", 3, "PRO", "IA", 3, "u", "Corte semanal como imagen para compartir", "El creador presume su semana con un toque. Hecho cuando viene en el correo del viernes."],
  ["350", 3, "PRO", "IA", 4, "u", "Programa de referidos", "Quien trae a un creador gana una parte de la comisión de la casa durante 12 meses. No cuesta si no hay ingreso. Hecho cuando se paga solo."],
  ["351", 3, "PRO", "IA", 3, "u", "Recargas por transferencia y en tienda", "Cuestan menos que la tarjeta y llegan a quien no tiene tarjeta. Hecho cuando una recarga por transferencia cae sola."],
  ["352", 3, "PRO", "IA", 2, "u", "Respuestas guardadas y registro de incidencias", "Para que soporte conteste igual siempre y se vea qué se repite. Hecho cuando hay un registro por semana."],
  ["353", 3, "PRO", "IA", 3, "u", "Regalar entradas con código", "Para promociones y para que el creador invite a diez personas a probar. Hecho cuando un código funciona una sola vez."],
  ["354", 3, "PRO", "IA", 3, "u", "Página pública del creador con próximas fechas", "Opcional: la enciende quien quiera. Hecho cuando un creador la comparte."],
  ["355", 3, "DAT", "IA", 2, "s", "Embudo por fuente y por tipo", "De mensaje a sala, de sala a sesión y de sesión a primer peso. Hecho cuando se ve dónde se cae la gente."],
  ["356", 3, "DAT", "A", 2, "m", "Costo por creador activado", "Dinero y horas por canal. Decide dónde poner el siguiente peso. Hecho con el primer mes calculado."],
  ["357", 3, "DAT", "IA", 2, "m", "Qué tienen en común los 20 mejores", "Tipo, precio, frecuencia y cómo anuncian, para buscar más como ellos. Hecho con el primer análisis."],
  ["358", 3, "DAT", "IA", 1, "s", "Lista de creadores en riesgo", "Cobraron y llevan 14 días sin transmitir. Hecho cuando el equipo la recibe cada lunes."],
  ["359", 3, "DAT", "A", 1, "s", "Una pregunta al espectador al salir", "«¿Volverías?» Sí o no. Mide la calidad de las salas. Hecho con las primeras 500 respuestas."],
  ["360", 3, "ADM", "P", 2, "m", "Cierre mensual de dinero", "Ingreso de la casa, comisión de tarjeta, garantías y nómina. Hecho con el primer cierre."],

  // ── Fase 4 · Los primeros 1,000 ───────────────────────────────────────
  ["401", 4, "ALI", "A", 3, "u", "Mapa de 30 agencias de TikTok LIVE", "De México y Colombia: nombre, cuántos anfitriones manejan y quién decide. Una agencia trae decenas de creadores de un golpe. Hecho con las 30 en el CRM."],
  ["402", 4, "ALI", "P", 2, "u", "Oferta para agencias", "Una parte de la comisión de la casa por sus anfitriones durante 12 meses, y un tablero propio. Hecho en una hoja."],
  ["403", 4, "ALI", "P", 4, "u", "Cerrar tres agencias piloto", "Con 50 anfitriones cada una. Hecho cuando las tres tienen fecha de arranque."],
  ["404", 4, "ALI", "A", 2, "u", "Capacitación para managers de agencia", "Una hora grabada: la jugada, el precio y los diseños. Hecho cuando una agencia la da sola."],
  ["405", 4, "ALI", "P", 3, "u", "Programa de 20 embajadores", "Creadores que ya cobran y activan a otros, con comisión. Hecho con 20 firmados."],
  ["406", 4, "ALI", "P", 3, "u", "Diez administradores de comunidades grandes", "Grupos de Facebook y WhatsApp por tipo de creador: ofrecerles una sala para su comunidad. Hecho con diez alianzas."],
  ["407", 4, "ALI", "P", 3, "u", "Cinco academias", "Música, idiomas y danza: clases abiertas de pago por la plataforma. Hecho con cinco pilotos."],
  ["408", 4, "ALI", "P", 3, "u", "Dos asociaciones profesionales", "Contadores, abogados o entrenadores: talleres de pago para sus miembros. Hecho con dos convenios."],
  ["409", 4, "ALI", "P", 2, "u", "Marcas que patrocinen retos", "Instrumentos, ropa deportiva o papelería: premios para los retos mensuales. Hecho con un patrocinador."],
  ["410", 4, "ALI", "P", 3, "u", "Taller «cobra por lo que sabes» en diez universidades", "Los estudiantes son creadores y tutores fáciles de activar. Hecho con diez talleres."],
  ["411", 4, "ALI", "P", 2, "u", "Presencia en tres reuniones de creadores", "Una charla corta con números reales vale más que un puesto. Hecho con tres charlas."],
  ["412", 4, "PRO", "IA", 4, "u", "Tablero para agencias", "Ver a sus anfitriones, lo que generan y su parte. Hecho cuando una agencia entra y lo usa."],
  ["413", 4, "ADM", "P", 3, "u", "Segundo líder de creadores", "Repetir la prueba de siete días. Hecho con la persona trabajando."],
  ["414", 4, "VEN", "P", 3, "u", "Cinco embajadores mandando mensajes por comisión", "Con el guion y el CRM. Hecho cuando traen 20 salas a la semana."],
  ["415", 4, "VEN", "P", 3, "u", "Programa para 20 cabezas de cartel", "Creadores de más de 100 mil seguidores con trato directo y evento propio. Hecho con 20 conversaciones y 5 fechas."],
  ["416", 4, "VEN", "P", 4, "u", "Primer evento faro", "Un nombre conocido en una sesión íntima con cupo. Meta: 300 entradas. Una noche que todos comentan. Hecho con el evento realizado."],
  ["417", 4, "VEN", "P", 3, "m", "Un evento faro al mes por tipo de creador", "Una fecha grande que jala a los demás. Hecho con tres meses seguidos."],
  ["418", 4, "VEN", "A", 2, "m", "Despertar a los dormidos cada mes", "A quien cobró y dejó de transmitir: un caso nuevo y una fecha. Hecho cuando sale cada mes."],
  ["419", 4, "VEN", "P", 2, "s", "Empujar la membresía", "A quien hace más de cuatro sesiones al mes: ingreso que se repite para él y para la casa. Hecho cuando 30 creadores la ofrecen."],
  ["420", 4, "VEN", "A", 2, "m", "Clínica de precio", "Sesión mensual para subir precios con casos reales. Hecho cuando el promedio por entrada pasa de $60."],
  ["421", 4, "VEN", "A", 2, "s", "Tabla de avance entre creadores", "Quién subió más esta semana, entre quienes quieran aparecer. Hecho cuando se comparte cada lunes."],
  ["422", 4, "MKT", "IA", 4, "u", "Cincuenta páginas por búsqueda", "Una por cada búsqueda con intención real y con casos verdaderos. Nada de relleno. Hecho con 50 publicadas."],
  ["423", 4, "CON", "A", 4, "u", "Doce tutoriales por tipo de creador en YouTube", "Una lista de reproducción por tipo. Hecho con las 12 publicadas."],
  ["424", 4, "MKT", "A", 4, "m", "Informe «cuánto ganan los creadores en vivo en México»", "Con datos propios, cada trimestre. La prensa publica datos, no anuncios. Hecho con el primer informe."],
  ["425", 4, "MKT", "P", 3, "u", "Prensa nacional", "Expansión, El Economista, Forbes México y Xataka México, con el informe como gancho. Hecho con dos notas."],
  ["426", 4, "CON", "P", 4, "u", "Mini documental de un caso", "Tres minutos: la vida de un creador antes y después. Hecho con el video publicado."],
  ["427", 4, "CON", "A", 2, "m", "Reto mensual con premio", "Los creadores publican su mejor clip de «el after». Contenido que no hacemos nosotros. Hecho con tres retos."],
  ["428", 4, "MKT", "A", 2, "u", "Colaboraciones pagadas por resultado", "Solo con creadores medianos y solo por creador activado, nunca por publicación. Hecho con cinco colaboraciones medidas."],
  ["429", 4, "MKT", "A", 2, "s", "Clips de salas reales", "Con permiso, 15 segundos de una sala en vivo sin mostrar al público. Hecho con 30 clips."],
  ["430", 4, "CON", "A", 2, "u", "Guía descargable por tipo de creador", "«Tu primer mes cobrando en vivo», con el plan día por día. Hecho con cinco guías."],
  ["431", 4, "MKT", "P", 2, "u", "Premio o reconocimiento del sector", "Postular a un premio de emprendimiento o innovación. Da credibilidad barata. Hecho con una postulación."],
  ["432", 4, "PRO", "IA", 4, "u", "Aplicación instalable con avisos", "Que el teléfono avise «ya empezó». Sube la asistencia. Hecho cuando el aviso llega en iPhone y en Android."],
  ["433", 4, "PRO", "IA", 4, "u", "Varios links por creador", "Un link por negocio; el extra se cobra al mes. Hecho cuando un creador tiene dos."],
  ["434", 4, "PRO", "IA", 3, "u", "Sala con cupo limitado", "«Solo 20 lugares.» La escasez sube el precio. Hecho cuando una sala se llena y cierra."],
  ["435", 4, "PRO", "IA", 3, "u", "Boleto anticipado", "Vender la entrada días antes de un evento faro. Hecho cuando un evento vende antes de abrir."],
  ["436", 4, "PRO", "IA", 4, "u", "Invitado en pantalla", "Dos personas transmitiendo en la misma sala. Hecho cuando un creador invita a otro."],
  ["437", 4, "PRO", "IA", 3, "u", "Moderadores nombrados por el creador", "Para salas grandes. Hecho cuando un moderador puede silenciar."],
  ["438", 4, "PRO", "A", 2, "u", "Evaluar una cartelera opcional", "Una página donde aparecen solo las salas que quieran. Revisarla contra la regla de no recomendar dentro de la app. Hecho con la decisión tomada."],
  ["439", 4, "PRO", "IA", 3, "u", "Cobro a público de otros países", "Tarjetas extranjeras y precios que se entiendan fuera de México. Hecho cuando alguien paga desde Colombia."],
  ["440", 4, "PRO", "A", 3, "u", "Retiros para creadores de otros países", "Elegir proveedor y costo. Sin esto no hay fase 5. Hecho con la decisión y la fecha."],
  ["441", 4, "PRO", "IA", 3, "u", "Resumen para el espectador", "Su recibo, a quién apoyó y cuándo vuelve a transmitir esa persona. Lo trae de regreso. Hecho cuando llega tras cada entrada."],
  ["442", 4, "DAT", "IA", 3, "u", "Retención por generación y valor por tipo", "Cuánto deja un creador en seis meses según su tipo. Decide a quién buscar. Hecho con la primera tabla."],
  ["443", 4, "ADM", "P", 1, "s", "Vigilancia semanal de fraude", "Contracargos, recargas raras y cuentas duplicadas. Hecho cuando hay un reporte cada lunes."],
  ["444", 4, "ADM", "P", 2, "m", "Tesorería", "El saldo de los usuarios es dinero que se debe: separarlo y conciliarlo cada mes. Hecho con tres cierres."],
  ["445", 4, "ADM", "P", 3, "u", "Aplicar lo que dijo el fiscalista", "Retenciones, constancias y facturas, si aplican. Hecho cuando el proceso corre solo."],
  ["446", 4, "ADM", "P", 2, "u", "Soporte los siete días", "Los en vivos son de noche y en fin de semana. Hecho con guardias definidas."],
  ["447", 4, "DAT", "IA", 2, "u", "Tablero público de transparencia", "Cuánto se ha pagado, a cuántos creadores y en cuántas sesiones. Hecho cuando está en línea."],
  ["448", 4, "ADM", "P", 2, "u", "Revisar la comisión para los grandes", "¿Conviene un trato especial para retener a las cabezas de cartel? Decidir con números. Hecho con la decisión tomada."],

  // ── Fase 5 · El millón ────────────────────────────────────────────────
  ["501", 5, "VEN", "P", 4, "u", "Creador ancla en Colombia", "Uno conocido que abra el país. Hecho con su primera sesión cobrada."],
  ["502", 5, "VEN", "P", 4, "u", "Creador ancla en Argentina", "Uno conocido que abra el país. Hecho con su primera sesión cobrada."],
  ["503", 5, "VEN", "P", 4, "u", "Creadores ancla en Perú y Chile", "Uno por país. Hecho con sus primeras sesiones cobradas."],
  ["504", 5, "MKT", "IA", 3, "u", "Páginas y diseños por país", "Moneda, ejemplos y horarios locales. El conversor de horarios ya existe en Materiales. Hecho con cuatro países."],
  ["505", 5, "ALI", "P", 3, "u", "Un embajador líder por país", "Por comisión, con el guion y el CRM. Hecho con cuatro líderes activos."],
  ["506", 5, "VEN", "P", 4, "m", "Tres eventos faro al mes", "Uno por cada tipo de creador principal. Hecho con tres meses seguidos."],
  ["507", 5, "VEN", "P", 3, "u", "Plan individual para 20 cabezas de cartel", "Cada uno con meta de $50,000 al mes: calendario, precio y membresía. Hecho con 20 planes firmados."],
  ["508", 5, "VEN", "A", 3, "u", "Membresías: 30 % de la puerta", "Es ingreso que se repite solo. Hecho cuando las membresías son el 30 % del total."],
  ["509", 5, "MKT", "A", 3, "u", "Temporadas y tablas por tipo de creador", "Con premios, para quien quiera aparecer. Hecho con la primera temporada cerrada."],
  ["510", 5, "MKT", "P", 4, "u", "Premios anuales «lo mejor en vivo»", "Una noche al año que la prensa cubre. Hecho con la primera edición."],
  ["511", 5, "MKT", "A", 4, "u", "Campaña de marca «nada se graba»", "La idea que nadie más puede decir. Hecho con la campaña en la calle y en redes."],
  ["512", 5, "ALI", "P", 4, "u", "Alianza para recargas baratas", "Con un banco, una fintech o una cadena de tiendas, para bajar la comisión de recarga. Hecho con un convenio firmado."],
  ["513", 5, "ADM", "P", 3, "u", "Decidir: inversión o caja", "Con los números de seis meses, decidir si conviene levantar capital. Hecho con la decisión escrita."],
  ["514", 5, "PRO", "A", 3, "u", "Evaluar salas uno a uno con agenda", "Consultas privadas con cita y precio por sesión. Hecho con la decisión y una prueba."],
  ["515", 5, "PRO", "IA", 4, "u", "Conexión para academias", "Que una academia venda sus clases desde su propio sitio. Hecho cuando una lo usa."],
  ["516", 5, "ADM", "P", 3, "u", "Equipo de soporte, moderación y finanzas", "Tres funciones que ya no puede cargar una persona. Hecho con las tres cubiertas."],
  ["517", 5, "ADM", "P", 3, "u", "Auditoría de seguridad y de cumplimiento", "Antes de que el tamaño llame la atención. Hecho con el informe y los pendientes cerrados."],
  ["518", 5, "DAT", "IA", 2, "m", "Proyección mensual contra la meta", "Dónde estaremos en 90 días si nada cambia. Hecho cuando sale cada mes."],
  ["519", 5, "VEN", "P", 3, "u", "Retener a las cabezas de cartel", "Lo que más duele es perder a un grande. Plan de trato, soporte y condiciones. Hecho con cero bajas en un trimestre."],
  ["520", 5, "MKT", "P", 3, "u", "Gira por cinco ciudades", "Ciudad de México, Monterrey, Guadalajara, Bogotá y Medellín: reunión con creadores locales. Hecho con las cinco."],
  ["521", 5, "CON", "A", 3, "s", "Programa semanal de la casa", "Un programa propio dentro de Video Room con creadores invitados. Hecho con ocho emisiones."],
  ["522", 5, "ALI", "P", 3, "u", "Alianza con una productora o red de canales", "Quien ya representa a muchos creadores. Hecho con un convenio."],
  ["523", 5, "PRO", "IA", 4, "u", "Inglés y portugués", "Para Estados Unidos y Brasil. Hecho cuando una sala corre completa en cada idioma."],
  ["524", 5, "MKT", "A", 3, "u", "Estudio de caso con un medio grande", "Un reportaje a fondo con números. Hecho con la publicación."],
  ["525", 5, "ADM", "P", 2, "m", "Tablero de dirección mensual", "Margen neto por cada peso de puerta, después de tarjeta y de nómina. Hecho con tres meses."],
  ["526", 5, "VEN", "A", 3, "u", "Escuela de creadores", "Curso gratuito de cuatro semanas. Cada generación son 200 creadores nuevos. Hecho con la primera generación."],
  ["527", 5, "PRO", "IA", 3, "u", "Paquetes de horas", "Vender 5 o 10 entradas juntas con descuento: recargas más grandes y menos comisión de tarjeta. Hecho cuando un paquete se vende."],
  ["528", 5, "DAT", "A", 2, "m", "Vigilar la mezcla: puerta contra envíos", "Lo que se manda adentro no deja comisión y sí cuesta tarjeta. Cuidar que la puerta sea la mayoría. Hecho con el dato cada mes."],
  ["529", 5, "MKT", "P", 2, "u", "Historia del fundador en un medio de negocios", "De Torreón para el mundo. Hecho con la nota publicada."],
  ["530", 5, "ADM", "P", 2, "u", "Celebrar el millón y fijar la siguiente meta", "Con el equipo y con los creadores que lo hicieron posible. Hecho cuando hay meta nueva."],
];
