// RLR
// 1095 frases de gratitud y crecimiento personal — Ricardo López Reyero (RLR).
// Una por día, siempre en el mismo orden, en loop infinito (getDailyPhrase()).
export const PHRASES: string[] = [
  "Gracias por este día que se me regala completo y nuevo, RLR",
  "Mi mundo interior crea mi mundo exterior, así que cuido lo que pienso, RLR",
  "Agradezco antes de pedir y pido desde la abundancia, no desde la falta, RLR",
  "Lo que puedo imaginar lo puedo crear, porque la imaginación es el puente al mundo físico, RLR",
  "Cada gratitud que escribo me deja en estado receptivo para ver lo que antes no veía, RLR",
  "Soy más listo de lo que pienso, y hoy lo voy a demostrar con hechos pequeños, RLR",
  "Doy las gracias por lo que tengo y por lo que todavía no llega pero ya está en camino, RLR",
  "Mi confianza en mí mismo, multiplicada por mi imaginación, es lo que voy a crear hoy, RLR",
  "Suelto experiencias pasadas que no me ayudaron y abro espacio para algo nuevo y próspero, RLR",
  "Hoy elijo respirar despacio una vez más, porque la conciencia empieza en el aire que entra, RLR",
  "Soy el guardián de mi tiempo, y por eso elijo dónde lo invierto con cuidado, RLR",
  "Doy gracias por lo que me ha pasado y por lo que no, porque ambas cosas me trajeron aquí, RLR",
  "Pausa el pretexto y entra a la acción: el momento exacto es ahora, RLR",
  "Hay mucho más en mí queriendo expresarse, y hoy le doy permiso de salir, RLR",
  "Cada problema tiene mínimo dos perspectivas, y elijo la que me fortalece, RLR",
  "El día que decido agradecer, el día decide regalarme algo más, RLR",
  "Mi atención es mi moneda más cara, y HOY elijo en qué la gasto o Invierto, RLR",
  "Observo mis pensamientos y me quedo solo con los que me fortalecen, RLR",
  "Empezar en cero no es un castigo, es la libertad de poder construir lo que quiera, RLR",
  "Leer es buscar la frase exacta que mi vida está esperando para cambiar, RLR",
  "Hoy hago algo difícil porque sé que del otro lado está la versión que quiero ser, RLR",
  "Agradezco a quienes están a mi alrededor: cada uno me está enseñando algo si lo dejo, RLR",
  "La abundancia no es exceso, es equilibrio y bienestar para todos, RLR",
  "Disfruto el segundo en el que estoy, porque es lo único que existe completo, RLR",
  "Agradezco mi salud, mi cuerpo y la respiración que no tengo que pedirle a nadie, RLR",
  "Lo que escribo hoy en mi cabeza, mañana lo veo en mi vida, RLR",
  "Pienso en grande y elijo ayudar a miles, porque hay espacio para hacerlo, RLR",
  "Hoy elijo creer un poco más en mí, aunque la prueba todavía no haya llegado, RLR",
  "Cuando agradezco, me vuelvo imán de lo que se parece a esa gratitud, RLR",
  "Mi vida no la cambian los grandes momentos, la cambian las pequeñas decisiones diarias, RLR",
  "Cierro este mes agradecido por el camino, sabiendo que el mejor recién empieza, RLR",
  "Solo empieza eso que estás postergando, ahorita, en este momento, RLR",
  "Cambia de mental a físico: la idea solo importa cuando aterriza en una acción, RLR",
  "Hoy hago la cosa difícil primero, y el resto del día se vuelve más ligero, RLR",
  "La disciplina es agradecer en silencio mientras hago lo que dije que iba a hacer, RLR",
  "Mi enfoque vale más que mi talento, y hoy lo cuido como mi recurso más escaso, RLR",
  "Hago menos cosas pero las hago mejor, porque profundizar es el atajo verdadero, RLR",
  "Cada NO a una distracción es un SÍ a la vida que estoy construyendo, RLR",
  "Una decisión clara hoy ahorra mil dudas mañana, RLR",
  "Hoy elijo terminar lo que empecé, porque empezar es fácil y terminar es lo que enseña, RLR",
  "Si me siento 50 minutos a contestar la pregunta más importante, encuentro respuestas que cambian años, RLR",
  "La repetición no es aburrida: es donde nace la maestría, RLR",
  "Lo que más temo hacer, casi siempre es lo que más necesito hacer, RLR",
  "Hoy escribo mi meta varias veces, porque lo que se repite se cree y lo que se cree se vuelve real, RLR",
  "Avanzar 1% diario suena poco, hasta que sumas un año y ves que duplicaste, RLR",
  "La acción imperfecta de hoy es mil veces mejor que el plan perfecto de la próxima semana, RLR",
  "La claridad no llega antes de moverte, llega mientras te mueves, RLR",
  "Cuido mi energía como cuido mi dinero: la invierto donde rinde, no donde la pierdo, RLR",
  "Hoy le digo gracias al “no” que recibí, porque me empujó al “sí” correcto, RLR",
  "La vida premia a quien itera, no a quien espera tener todo perfecto antes de salir, RLR",
  "Lo que hoy parece imposible, en cien iteraciones se vuelve obvio, RLR",
  "Hago lo que veo: confío en lo que ya está claro y avanzo con eso, RLR",
  "El esfuerzo de hoy es la suerte de mañana disfrazada, RLR",
  "Cada día que persevero estoy escribiendo una historia que algún día querré contar, RLR",
  "La constancia es la forma más bonita del amor propio, RLR",
  "Hoy regalo mi mejor versión, aunque nadie esté mirando, porque yo me estoy mirando, RLR",
  "Las grandes vidas se construyen con pequeñas victorias diarias acumuladas, RLR",
  "Termina lo simple antes de buscar lo complejo: casi siempre es suficiente, RLR",
  "Hoy agradezco mi capacidad de empezar de nuevo cuantas veces haga falta, RLR",
  "Mi confianza en mí mismo es la base de todo lo que voy a crear, RLR",
  "A mayor confianza, mejores preguntas; a mejores preguntas, mejor vida, RLR",
  "Tengo una mente millonaria: pienso desde la abundancia, no desde la escasez, RLR",
  "Mi dinero trabaja para mí y me genera cada vez más dinero, RLR",
  "Soy un excelente receptor: estoy abierto y dispuesto a recibir grandes cantidades de bien en mi vida, RLR",
  "Promuevo mi valor con pasión y entusiasmo, sin pedir disculpas por existir, RLR",
  "Lo que aprendí sobre el dinero fue la manera de otros; yo elijo la mía, RLR",
  "Me comprometo a aprender y crecer constantemente, RLR",
  "Administro lo que tengo con cariño, y lo que tengo crece, RLR",
  "Soy capaz de mucho más de lo que mi cabeza me deja ver, y hoy lo confirmo, RLR",
  "La envidia es solo un GPS apuntando a lo que también yo puedo construir, RLR",
  "Cuando la duda llega, agradezco que aparezca y la dejo pasar, RLR",
  "Mi pasado no es mi techo, solo es mi punto de partida, RLR",
  "Confío en que las puertas correctas se abren cuando estoy en el lugar correcto, haciendo lo correcto, RLR",
  "Soy responsable de mi vida al 100%, y eso es la mejor noticia, porque significa que también la puedo cambiar, RLR",
  "Hoy me hablo como le hablaría a alguien que amo, porque también me amo, RLR",
  "Mis pensamientos no son la verdad, son solo opciones que puedo elegir o soltar, RLR",
  "La paz interior no es ausencia de retos, es confianza de poder con ellos, RLR",
  "Soy más fuerte que mi peor día y más sabio que mi peor error, RLR",
  "Cada vez que me elijo, le doy permiso a otros de elegirse, RLR",
  "Mi peor crítico vive entre mis dos orejas, y hoy lo invito a calmarse, RLR",
  "Lo que me digo en silencio se convierte en mi voz pública con el tiempo, RLR",
  "Hoy decido pensar bonito de mí, aunque sea como ejercicio, RLR",
  "Mi historia personal no me define, mi siguiente decisión sí, RLR",
  "Tengo permiso de cambiar de opinión cuando aparece mejor información, RLR",
  "La comparación es ladrona de paz; agradezco mi camino único, RLR",
  "Cada vez que respiro profundo, regreso a mi centro, RLR",
  "La confianza se construye con promesas pequeñas que me cumplo a mí mismo, RLR",
  "Mi mente es un instrumento poderoso, hoy elijo afinarla con buenas ideas, RLR",
  "Cierro marzo confiando en que ya estoy listo para lo que sigue, RLR",
  "Soy el creador, no la víctima, de mi vida, RLR",
  "Leo todos los días, porque cada libro es una conciencia ofreciéndome lo que descubrió, RLR",
  "La frase exacta para cambiar mi vida me está esperando en la página de algún libro, RLR",
  "No importa la cantidad de libros leídos; importa cuántas frases entraron tan duro que me transformaron, RLR",
  "Cada libro abierto es un mentor disponible 24/7 al precio de unas monedas, RLR",
  "Leer 10 páginas al día es leer más de 10 libros al año, RLR",
  "El conocimiento que no se aplica es entretenimiento caro disfrazado de progreso, RLR",
  "Hoy aprendo algo y lo enseño en cuanto pueda, porque enseñar es aprender el doble, RLR",
  "Las mejores preguntas valen más que las mejores respuestas, RLR",
  "Pregunto con curiosidad, escucho con humildad, aplico con valentía, RLR",
  "Lo que no sé hoy, mañana puedo saberlo si me siento a aprenderlo, RLR",
  "La ignorancia no es vergüenza; quedarse en ella sí, RLR",
  "Cada error es un libro que no compré, pero igual me regaló una lección, RLR",
  "Hoy leo algo que me confronte, porque solo en lo incómodo crezco, RLR",
  "La sabiduría es conocimiento más experiencia más tiempo más humildad, RLR",
  "Documentar lo que aprendo es regalárselo al yo del futuro y a quien venga después, RLR",
  "Lo que escribo se queda; lo que solo pienso se va, RLR",
  "Mis cuadernos son mis mejores compañeros silenciosos, RLR",
  "Compartir mis pensamientos hace avanzar a mi sociedad y a mí mismo, RLR",
  "Hoy le pregunto a alguien sabio una sola cosa, y guardo la respuesta como un tesoro, RLR",
  "La curiosidad es el motor más limpio que puedo tener, RLR",
  "Mejor preguntar 10 veces que vivir 10 años con una duda, RLR",
  "Si una idea se repite en tres lugares distintos, probablemente es una pista del universo, RLR",
  "Releer un libro a los dos años es leer un libro nuevo, porque yo soy nuevo, RLR",
  "Hoy regalo un libro a alguien, porque las ideas se multiplican cuando se sueltan, RLR",
  "La biblioteca personal es la herencia más valiosa que puedo dejar, RLR",
  "Aprender es la forma más segura de no envejecer, RLR",
  "Lo que entiendo lo puedo explicar simple; lo que no entiendo lo explico complicado, RLR",
  "Hoy desaprendo algo que ya no me sirve para tener espacio para algo nuevo, RLR",
  "Me rodeo de libros, ideas y personas que me empujen un poco hacia arriba, RLR",
  "Cierro abril sabiendo que el yo más sabio del mundo siempre es el yo del próximo año, RLR",
  "Maximizo por valor primero, y la monetización viene después como consecuencia, RLR",
  "El dinero es la captura natural del valor que generas para los demás, RLR",
  "Hoy busco resolver un problema real, no inventar uno bonito, RLR",
  "Si lo que hago no le sirve a nadie, no es servicio, es ego con corbata, RLR",
  "Servir es la forma más rápida de salir de mi cabeza y entrar en mi corazón, RLR",
  "Hoy ayudo a alguien sin que me lo pidan, en pequeño, solo porque puedo, RLR",
  "La empresa más sólida es la que sus clientes recomendarían aunque no les pagaran, RLR",
  "Pongo a la persona correcta en el puesto correcto, empezando por mí mismo, RLR",
  "Cuando dejo de pelearme con el mundo y empiezo a servirlo, el mundo empieza a servirme, RLR",
  "Mi trabajo bien hecho es una oración silenciosa, RLR",
  "Hoy alguien me bendice y yo ni me entero, porque ese es el chiste de servir bien, RLR",
  "La gratitud convierte lo que tengo en suficiente, y lo suficiente en abundante, RLR",
  "Compartir mi conocimiento no me hace pobre, me hace influyente, RLR",
  "Hoy doy más de lo que cobré, porque ahí es donde se construye reputación, RLR",
  "La abundancia no se mide solo en dinero: también en salud, paz, energía y libertad, RLR",
  "Soy generoso con lo que tengo, y por eso me llega más para seguir siendo generoso, RLR",
  "Doy las gracias por mis clientes, mis jefes, mis colegas: todos me están enseñando, RLR",
  "Cuando ayudo sin esperar nada, casi siempre recibo lo que ni había imaginado, RLR",
  "La verdadera riqueza es tener tiempo para mi gente y energía para disfrutarla, RLR",
  "Hoy felicito sinceramente a alguien por algo que admiro de él, RLR",
  "Doy las gracias por la persona que me atiende en cada lugar al que voy, RLR",
  "Mi sonrisa hoy puede ser el milagro pequeño que alguien estaba pidiendo, RLR",
  "Si me siento a contar mis bendiciones, se me acaba el día antes que la lista, RLR",
  "Doy lo mejor que tengo, aunque tenga poco, porque lo mejor siempre alcanza, RLR",
  "La forma más rápida de sentirme rico es agradecer lo que ya tengo, RLR",
  "Hoy le digo “gracias” a alguien al que nunca le he dado las gracias, RLR",
  "La prosperidad personal genera bienestar colectivo: subir yo es subir a todos un poco, RLR",
  "Pago lo que debo a tiempo, porque eso me devuelve la dignidad y me abre la siguiente puerta, RLR",
  "Hoy bendigo a quien me debe algo y suelto la deuda emocional, RLR",
  "Cierro mayo sabiendo que dar y recibir son la misma cosa vista desde dos lados, RLR",
  "La forma de cobrar también enseña: cobro con honor lo que valgo, sin disculpas, RLR",
  "Hoy abrazo a mi gente más cerca, porque el tiempo con ellos no es infinito, RLR",
  "Mis padres hicieron lo mejor que pudieron con lo que tenían, y eso es suficiente, RLR",
  "Doy las gracias por mi pareja, por mis hijos, por las personas que me eligieron, RLR",
  "Lo que más necesita la gente que amo no es mi dinero, es mi presencia, RLR",
  "Hoy escucho de verdad, sin pensar qué voy a contestar, RLR",
  "Una llamada de tres minutos puede cambiarle el día a alguien que extraño, RLR",
  "Las pláticas profundas alimentan más que las superficiales, aunque cuesten más, RLR",
  "Perdono a quien me dañó, no porque tenga razón, sino porque yo merezco paz, RLR",
  "Hoy pido perdón a alguien sin condiciones ni explicaciones largas, RLR",
  "Las relaciones se cuidan diario, no solo en aniversarios y cumpleaños, RLR",
  "Mi casa es mi templo, y la cuido con la misma reverencia, RLR",
  "Doy las gracias por discutir con alguien que me ama lo suficiente para corregirme, RLR",
  "Hoy le digo “te quiero” a alguien que necesita oírlo, antes de que sea tarde, RLR",
  "Los amigos verdaderos se notan cuando uno deja de tener nada que ofrecer, RLR",
  "Cuido mis relaciones como cuido mis plantas: con agua, sol y atención constante, RLR",
  "Hoy dejo de querer cambiar a alguien y simplemente lo amo como es, RLR",
  "Las personas no llegan por casualidad: cada una es un mensaje, una clase o una bendición, RLR",
  "Mi familia no es perfecta, y por eso es mía y la amo, RLR",
  "Doy las gracias por las personas difíciles, porque me enseñan paciencia, RLR",
  "Hoy rompo una racha de orgullo y doy el primer paso que sé que tengo que dar, RLR",
  "Las palabras que salen de mi boca pintan el ambiente de mi casa, RLR",
  "Si me corrijo a mí mismo, ya no tengo que corregir tanto a los demás, RLR",
  "Hoy regalo un detalle pequeño que diga “te tengo en mente”, RLR",
  "Los conflictos bien manejados acercan más que la calma fingida, RLR",
  "Mi pareja no vino a completarme, vino a caminar conmigo mientras me completo solo, RLR",
  "Hoy me detengo a preguntarle a alguien cómo está, de verdad, RLR",
  "La paciencia con la familia es el examen final del crecimiento personal, RLR",
  "Doy las gracias por las despedidas, porque me enseñaron a valorar a los que se quedaron, RLR",
  "Hoy elijo ver lo bueno de la gente que me rodea antes que lo que me molesta, RLR",
  "Cierro junio sabiendo que las personas son la verdadera moneda de la vida, RLR",
  "Doy las gracias por mi cuerpo, que me lleva a todos lados sin pedir mucho a cambio, RLR",
  "Mi salud no es un accidente, es una decisión repetida miles de veces al día, RLR",
  "Hoy elijo lo que como, sabiendo que es información para mis células, RLR",
  "El movimiento es medicina barata que rara vez me receto solo, RLR",
  "Dormir bien hoy es ser amable con el yo de mañana, RLR",
  "Tomo agua como acto de respeto a mi cuerpo, RLR",
  "La respiración profunda es la oración más simple que existe, RLR",
  "Hoy camino al sol unos minutos, porque el cuerpo recuerda lo que la mente olvida, RLR",
  "Cuido mi salud no para vivir más, sino para vivir mejor el tiempo que viva, RLR",
  "Mi energía es el activo más caro que tengo, y la cuido como tal, RLR",
  "Hoy le digo gracias a mi corazón por seguir latiendo sin que yo se lo pida, RLR",
  "Lo que como, lo que veo y lo que escucho son ingredientes de la persona que voy a ser, RLR",
  "La comida real alimenta el cuerpo; la comida procesada lo entretiene, RLR",
  "Hoy descanso sin culpa, porque el descanso también es trabajo, RLR",
  "Mi peso ideal es el que me deja moverme con alegría, no el que me dicta el espejo, RLR",
  "Sudar un rato hoy es ahorrar visitas al doctor mañana, RLR",
  "La gratitud es mi vitamina más barata y más efectiva, RLR",
  "Hoy estiro mi cuerpo cinco minutos, porque le debo más de lo que le doy, RLR",
  "Comer despacio es masticar la vida, no solo la comida, RLR",
  "Mi cuerpo me habla todo el día; hoy lo escucho, RLR",
  "La salud mental también es salud, y hoy la cuido sin pedirle disculpas a nadie, RLR",
  "Una caminata cambia más estados de ánimo que mil consejos, RLR",
  "Hoy apago las pantallas una hora antes de dormir, porque mi cerebro me lo agradecerá, RLR",
  "Cuido mi postura, porque la postura es un pensamiento físico, RLR",
  "Mi cuerpo perdona mucho, pero yo aprendo a no abusar de su paciencia, RLR",
  "La fuerza física se construye igual que la fuerza mental: con repetición y voluntad, RLR",
  "Hoy salgo a la naturaleza un rato, aunque sea cinco minutos, RLR",
  "Mi piel, mis huesos y mis músculos están a mi servicio: les doy las gracias hoy, RLR",
  "Lo que entra por mis ojos también es comida, y hoy elijo qué dejo entrar, RLR",
  "Soy responsable de mi cuerpo, y eso es libertad, no carga, RLR",
  "Cierro julio agradecido por estar vivo y sano un día más, RLR",
  "Soy el guardián de mi tiempo, y por eso elijo a quién y a qué se lo regalo, RLR",
  "Mi atención es lo que el mundo más quiere; hoy me la quedo yo, RLR",
  "El día tiene 24 horas, y hoy las uso a propósito, no por inercia, RLR",
  "Decir “no” a tiempo me regala horas que valen oro, RLR",
  "Cada hora viendo lo que no me suma es una hora menos para construir lo que quiero, RLR",
  "Hoy paso menos tiempo en pantallas y más tiempo en mi vida, RLR",
  "La paz que sentí cuando dejé de scrollear no me la devuelve ningún video viral, RLR",
  "Mi cabeza piensa más claro cuando no la inundo con la vida ajena, RLR",
  "Hoy hago una sola cosa a la vez, y la hago bien, RLR",
  "La multitarea me robaba calidad sin que yo me diera cuenta, RLR",
  "El silencio no es ausencia, es donde nacen mis mejores ideas, RLR",
  "Hoy estoy 30 minutos sin teléfono, solo conmigo, y descubro algo, RLR",
  "Mi tiempo libre es la materia prima de mis sueños, no debo regalárselo a las apps, RLR",
  "Doy las gracias por las horas que ya no gasto en redes, porque las uso en mi vida real, RLR",
  "Lo que mido lo mejoro: hoy mido a dónde se me va el día, RLR",
  "La urgencia ajena casi nunca debe ser mi prioridad, RLR",
  "Hoy llego cinco minutos antes a algo, porque la puntualidad es un mensaje silencioso de respeto, RLR",
  "Tengo permiso de no contestar al instante; el mundo aprende a esperar, RLR",
  "Cada minuto invertido en mí mismo es un minuto que rinde toda la vida, RLR",
  "Hoy bloqueo dos horas para algo importante, sin interrupciones, y veo qué pasa, RLR",
  "Mi calendario refleja lo que de verdad me importa, RLR",
  "Doy las gracias por las pausas que me obligué a tomar, porque ahí encontré claridad, RLR",
  "El descanso programado es trabajo de élite, RLR",
  "Hoy aprendo a aburrirme un rato sin sacar el celular, RLR",
  "Mi mente vacía es fértil, no es perezosa, RLR",
  "La velocidad sin dirección solo es ruido caro, RLR",
  "Hoy decido qué es importante y dejo que lo demás espere o se caiga solo, RLR",
  "Lo que no agendo, no pasa; lo que agendo, casi siempre pasa, RLR",
  "Cierro agosto sabiendo que el tiempo bien usado es la mejor riqueza, RLR",
  "Mañana arranco con una sola cosa importante en la mira, RLR",
  "Mi atención sostenida es mi superpoder más subestimado, RLR",
  "Soy un puente entre la idea y el mundo físico, y hoy lo cruzo, RLR",
  "Lo que imagino con detalle, agradecido por adelantado, empieza a llegar, RLR",
  "Hay ideas en mí esperando turno para salir; hoy le doy turno a una, RLR",
  "Mi imaginación no es escape, es plano arquitectónico, RLR",
  "Deseo, imagino, escribo, actúo: este es el camino, RLR",
  "Cada idea que traigo al mundo lo cambia un poco para las siguientes generaciones, RLR",
  "Hoy escribo una idea que tengo desde hace tiempo, aunque sea una hoja, RLR",
  "Las ideas no se me ocurren a mí, pasan por mí; mi trabajo es bajarlas, RLR",
  "La página en blanco es una invitación, no una amenaza, RLR",
  "Hoy itero algo en lugar de empezarlo de cero, porque iterar es donde está el oro, RLR",
  "La primera versión es para que exista; las demás son para que valga la pena, RLR",
  "Si lo puedo describir, lo puedo prototipar, RLR",
  "Hoy mejoro algo que ya existe, en pequeño, en mi entorno, RLR",
  "La curiosidad es el inicio de todo invento, RLR",
  "Pregunto “¿y si…?” más veces al día, RLR",
  "Hoy combino dos cosas que nunca había combinado y veo qué sale, RLR",
  "Lo que me apasiona es una pista, no un capricho, RLR",
  "Mi creatividad no se acaba; se oxida cuando no la uso, RLR",
  "Hoy escribo 10 ideas malas, porque entre ellas siempre hay una buena escondida, RLR",
  "Las grandes ideas casi siempre empiezan sonando ridículas, RLR",
  "Hoy le pregunto a la inteligencia artificial algo que me daba pereza investigar, RLR",
  "La IA es una palanca que multiplica lo que ya soy, no lo que no soy, RLR",
  "Lo que antes tardaba meses, hoy se puede hacer en minutos: aprovecho la herramienta, RLR",
  "Hoy creo algo, aunque sea pequeño, solo por el placer de crear, RLR",
  "Mi imaginación es mi superpoder más subestimado, RLR",
  "Imaginar mi mejor versión, en detalle, ya es empezar a serla, RLR",
  "Hoy le pongo nombre a un proyecto que tenía guardado, porque lo nombrado se vuelve real, RLR",
  "La creación es más sagrada que la crítica, RLR",
  "Hoy escribo y mañana edito; nunca al revés, RLR",
  "Cierro septiembre con una idea más clara de lo que quiero traer al mundo, RLR",
  "El mismo lugar visto desde otra perspectiva se vuelve otro lugar, RLR",
  "Hoy le agradezco a un problema, porque me está enseñando algo que no quería aprender de otro modo, RLR",
  "Lo que parecía mala suerte, con tiempo, casi siempre fue protección, RLR",
  "La perspectiva alta convierte tragedia en aprendizaje, RLR",
  "Hoy subo dos metros mentalmente para ver mi vida completa, no solo el detalle, RLR",
  "Lo que más me cuesta hoy es exactamente lo que necesito para ser quien quiero ser, RLR",
  "Doy las gracias por el “no” que recibí, porque me empujó al “sí” correcto, RLR",
  "Cada cierre es la antesala de algo nuevo que todavía no veo, RLR",
  "Hoy bendigo lo que perdí, porque liberó espacio para lo que vino, RLR",
  "La vida no me pasa, me responde, RLR",
  "Lo que envío al mundo regresa: a veces tarde, casi siempre con intereses, RLR",
  "Hoy reviso de qué me estoy quejando y veo si se puede convertir en propuesta, RLR",
  "Quejarse es entregarle el control a quien no lo merece, RLR",
  "Doy las gracias por mis errores, porque me ahorraron errores más caros después, RLR",
  "La paciencia es fe en cámara lenta, RLR",
  "Hoy confío en que el tiempo va a acomodar lo que yo no puedo acomodar hoy, RLR",
  "La fe no es certeza; es disposición a actuar sin certeza, RLR",
  "Doy las gracias por lo que no entiendo todavía, sabiendo que algún día lo entenderé, RLR",
  "Lo que hoy parece final, mañana se ve como capítulo, RLR",
  "Hoy bendigo a quien me hirió, porque me ayudó a poner un límite que ya necesitaba, RLR",
  "La vida me está hablando todo el tiempo; hoy elijo escucharla, RLR",
  "Cada coincidencia es una invitación a poner atención, RLR",
  "Hoy noto tres pequeños milagros que casi siempre paso por alto, RLR",
  "Estoy haciendo milagros constantemente; lo único que cambia es mi conciencia de ellos, RLR",
  "La presencia es el único lugar donde la vida realmente sucede, RLR",
  "Hoy estoy aquí, completo, sin querer estar en otro lado, RLR",
  "Doy las gracias por estar vivo, sin condición, sin pero, sin todavía, RLR",
  "La vida no es un problema que resolver; es un misterio que vivir, RLR",
  "Hoy le encuentro sentido a algo que parecía no tenerlo, RLR",
  "Todo lo que es, es perfecto a su manera, aunque tarde un rato en verse así, RLR",
  "Cierro octubre más agradecido de lo que empecé, RLR",
  "Tengo el coraje de cambiar lo que no funciona, empezando por mí, RLR",
  "Mejorar requiere valentía, y hoy decido tenerla, RLR",
  "Hoy suelto algo que ya cumplió su tiempo en mi vida, RLR",
  "Lo que aprieto se va; a lo que abro espacio se queda, RLR",
  "Doy las gracias por mis miedos, porque me muestran exactamente dónde está mi siguiente puerta, RLR",
  "Cruzar el miedo me da más confianza que cualquier discurso motivacional, RLR",
  "Hoy hago una llamada que vengo postergando hace meses, RLR",
  "La incomodidad es la moneda con la que se paga el crecimiento, RLR",
  "Lo que tengo aguantando con esfuerzo, casi siempre tengo que soltar, RLR",
  "Hoy perdono al yo del pasado por las decisiones que tomó con la información que tenía, RLR",
  "No puedo cambiar el pasado, pero puedo cambiar el significado que le doy, RLR",
  "Hoy reescribo una historia vieja con palabras nuevas, RLR",
  "Cada cierre bien hecho es más importante que cualquier inicio apresurado, RLR",
  "Decir adiós con gratitud me deja libre para lo que sigue, RLR",
  "Hoy elijo estar más en paz que tener la razón, RLR",
  "Los apegos me roban más que las pérdidas, RLR",
  "Doy las gracias por las puertas que se cerraron, porque me obligaron a buscar la mía, RLR",
  "Lo que ya no me funciona, me funcionó cuando me funcionaba: gracias y adiós, RLR",
  "Hoy hago las paces con un capítulo de mi vida que tenía abierto sin querer, RLR",
  "El cambio empieza con una decisión interna, no con una circunstancia externa, RLR",
  "Hoy doy un paso pequeño hacia algo grande que vengo soñando, RLR",
  "La valentía no es no tener miedo, es hacerlo aunque tenga miedo, RLR",
  "Doy las gracias por las personas que ya no están en mi vida; cada una me trajo hasta aquí, RLR",
  "Confío en que estoy exactamente donde tengo que estar para llegar a donde quiero estar, RLR",
  "Hoy elijo un nuevo hábito y le doy 30 días sin negociar, RLR",
  "Lo que repito, se vuelve quien soy, RLR",
  "Cada yo viejo que muere deja nacer un yo nuevo más amplio, RLR",
  "Hoy me reinvento un poco, en pequeño, sin necesidad de explicárselo a nadie, RLR",
  "Como todo el mundo acaba dándose cuenta, nos casamos con nuestros asuntos pendientes; hoy resuelvo uno, RLR",
  "Cierro noviembre con menos peso del que cargaba al empezar, RLR",
  "Doy las gracias por el año que vivo, exacto como lo viví, RLR",
  "Lo que aprendí este año vale más que lo que conseguí, RLR",
  "Hoy reviso mis tres mejores decisiones del año y las celebro, RLR",
  "Las personas que se quedaron a mi lado merecen mi gratitud explícita, RLR",
  "Hoy le escribo a alguien para decirle el bien que me hizo este año, RLR",
  "Lo que sembré este año lo veré crecer en los próximos, RLR",
  "Doy las gracias por los proyectos que no salieron, porque me enseñaron lo que sí soy, RLR",
  "Cierro este año perdonando lo que me costó perdonar, RLR",
  "Hoy escribo lo que ya quiero soltar para no llevarlo al año que viene, RLR",
  "La gratitud al cierre es semilla para la apertura, RLR",
  "Doy las gracias por mi salud, mi gente y mi capacidad de seguir, RLR",
  "Hoy imagino, en detalle, el yo del próximo año, agradecido de antemano, RLR",
  "Lo que escribo, lo manifiesto; hoy escribo lo que viene, RLR",
  "Mis metas no son listas, son promesas que me hago en silencio, RLR",
  "La vida me ha dado más de lo que pedí, aunque no siempre como lo pedí, RLR",
  "Hoy reconozco que crecí, aunque a veces no se sintiera así, RLR",
  "Mi mejor versión todavía no llega; eso me emociona, no me angustia, RLR",
  "Doy las gracias por los maestros disfrazados de problemas, RLR",
  "Hoy bendigo el camino recorrido y el que falta por recorrer, RLR",
  "Termino el año más libre, más sabio y más mío que cuando empezó, RLR",
  "Lo que resistí, eventualmente entendí o solté, RLR",
  "Doy las gracias por el techo, la cama y la mesa: cuántas personas no las tienen, RLR",
  "La abundancia empieza cuando dejo de contar lo que falta y empiezo a contar lo que sobra, RLR",
  "Hoy preparo el terreno para sembrar lo que quiero ver florecer, RLR",
  "Cada día agradecido es un ladrillo de una vida buena, RLR",
  "Mi historia personal vale, mi voz importa, mi camino cuenta, RLR",
  "Doy las gracias por leer, escribir, pensar y soñar; no todos pueden hacerlo libremente, RLR",
  "La gratitud es el atajo más antiguo y más subestimado para una buena vida, RLR",
  "Hoy cierro los ojos un momento y me doy cuenta de que ya tengo bastante, RLR",
  "Soy bendito y bendigo: ese es mi rol en este mundo, RLR",
  "Gracias, gracias, gracias: por todo lo que pasó, por lo que pasa y por lo que viene, RLR",
  "La gratitud no es un sentimiento bonito, es un suelo donde puedo pararme cuando todo lo demás tiembla, RLR",
  "Hoy no espero a sentir agradecimiento; lo digo y dejo que el sentimiento llegue después si quiere, RLR",
  "Decir “gracias” antes de saber por qué ya es ejercitar un músculo que algún día me va a sostener, RLR",
  "Cuando no tengo claridad, la gratitud por lo simple me la regresa, RLR",
  "Agradezco mi respiración, que no me pidió permiso para empezar y no me avisará cuando termine, RLR",
  "Hoy doy las gracias por las cosas que estaban a punto de salir mal y no salieron mal, RLR",
  "Lo que ya tengo es suficiente para hoy; mañana ya hablaré con mañana, RLR",
  "La gratitud me recuerda que no soy el centro del universo, y eso me alivia más de lo que creía, RLR",
  "Hoy le agradezco a mi cuerpo que me cargó hasta aquí, aunque a veces lo trate como si fuera obligación suya, RLR",
  "Doy las gracias por las personas que me quisieron y ya no están, porque ese amor no se fue, se quedó hecho yo, RLR",
  "Hoy agradezco lo que me incomoda, porque lo cómodo casi nunca me hizo crecer, RLR",
  "La gratitud silenciosa, sin testigos, es la que más me cambia por dentro, RLR",
  "Doy las gracias por la electricidad que llega sin pedir, por el agua que sale del grifo, por el techo: cosas que millones rezan por tener, RLR",
  "Hoy bendigo mi falta, porque está señalando exactamente lo que tengo que crear, RLR",
  "Agradezco las pérdidas que dolieron, porque me enseñaron qué cuidar mejor la próxima vez, RLR",
  "La gratitud no niega el dolor; lo abraza y lo deja respirar, RLR",
  "Hoy le digo gracias a mi mente, aunque a veces me cueste convivir con ella, RLR",
  "Cuando me siento poco, cuento bendiciones; cuando me siento mucho, también, RLR",
  "Doy las gracias por el lugar exacto donde estoy parado ahora, sin negociar con la geografía, RLR",
  "Hoy agradezco a quien me dijo “no”, porque me regaló espacio para encontrar a quien sí, RLR",
  "La queja y la gratitud no caben en la misma respiración; hoy elijo cuál respiro, RLR",
  "Agradezco mis lágrimas, porque también son una forma honesta de hablar, RLR",
  "Hoy le doy gracias al silencio, que escuchó todo lo que nadie quiso oír, RLR",
  "Doy las gracias por mis dudas, porque significan que sigo despierto, RLR",
  "Agradezco la luz del día sin pedirle que dure más de la cuenta, RLR",
  "Hoy, antes de pedir algo, hago una lista de tres cosas que ya recibí, RLR",
  "La gratitud por lo pequeño me prepara para recibir lo grande sin perderme en ello, RLR",
  "Doy las gracias por mi capacidad de elegir, aunque a veces elija mal, RLR",
  "Hoy agradezco no haber sido escuchado en algún momento, porque tuve que aprender a escucharme yo, RLR",
  "La gratitud verdadera no se nota en la cara, se nota en cómo trato a los demás esa tarde, RLR",
  "Cierro este mes sabiendo que la gratitud, repetida, deja de ser ejercicio y se vuelve forma de ser, RLR",
  "Hago lo que me toca y suelto lo que no me toca; ahí está el secreto, RLR",
  "Hoy actúo sin garantía, porque ninguna acción importante viene con recibo, RLR",
  "Empujar más fuerte no siempre es la respuesta; a veces lo correcto es soltar el remo, RLR",
  "La rendición no es derrota, es dejar de pelearme con lo que ya pasó, RLR",
  "Hoy hago mi mejor esfuerzo y entrego el resultado a algo más grande que mi ego, RLR",
  "Trabajo como si todo dependiera de mí y agradezco como si nada dependiera de mí, RLR",
  "Hay cosas que se logran empujando y otras que solo se logran quitando obstáculos: hoy reconozco cuál es cuál, RLR",
  "Cuando empujo desde el miedo, todo cuesta el doble; cuando empujo desde la fe, casi se mueve solo, RLR",
  "Hoy hago mi parte sin querer hacer la parte de los demás, RLR",
  "Lo que es para mí no se va, aunque parezca tardarse; lo que no es para mí se va, aunque me duela soltarlo, RLR",
  "Hoy descanso sin sentir que debo justificarlo con productividad mañana, RLR",
  "La rendición es confiar lo suficiente para dejar de actuar desde el control, RLR",
  "Suelto el cómo y me quedo con el qué; el universo es más creativo que yo en los caminos, RLR",
  "Hoy hago una sola cosa con todo el cuerpo en ella, y eso ya es mucho, RLR",
  "La urgencia rara vez crea bien; la presencia casi siempre crea bien, RLR",
  "Hoy elijo terminar lo que empecé en lugar de empezar algo nuevo para escapar, RLR",
  "Cuando no sé qué hacer, lo primero que hago es no hacer nada un rato, RLR",
  "La acción que viene de la calma es diez veces más eficiente que la que viene del pánico, RLR",
  "Hoy actúo en la dirección de lo que quiero, aunque el primer paso parezca insignificante, RLR",
  "Soltar el resultado no es dejar de querer; es dejar de aferrarme, RLR",
  "Hoy le agradezco a la pausa, que me ahorró decisiones de las que después me hubiera arrepentido, RLR",
  "La constancia silenciosa rinde más que el entusiasmo ruidoso, RLR",
  "Hoy elijo el camino largo si es el camino limpio, RLR",
  "Lo que tengo que hacer hoy es exactamente lo que tengo en frente; no busco más lejos, RLR",
  "La rendición es saber que no soy el director de la película, solo soy el protagonista, RLR",
  "Hoy entrego lo que llevo cargando sin permiso del mundo, RLR",
  "Termino mi día revisando qué hice y qué no, sin castigarme por ninguno de los dos, RLR",
  "Cierro febrero con manos que se mueven y corazón que descansa, RLR",
  "La confianza no es ausencia de duda, es seguir caminando con la duda al lado, RLR",
  "Cuando dudo, recuerdo todas las veces que ya superé algo que no creía poder superar, RLR",
  "Mi historia personal es prueba suficiente: he salido de cosas peores, en silencio, sin que nadie aplaudiera, RLR",
  "La duda no es enemiga, es solo una pregunta que todavía no tiene respuesta, RLR",
  "Hoy le doy gracias a mi inseguridad, porque me obliga a estudiar más, prepararme más, escuchar más, RLR",
  "Confiar en mí no es saberlo todo, es saber que voy a averiguar lo que no sé, RLR",
  "Cuando todo el mundo duda de mí y yo también, recuerdo que esa votación interna es la única que cuenta, RLR",
  "La confianza se gasta y se recarga; hoy hago algo pequeño que la recargue, RLR",
  "No tengo que ser el mejor; tengo que ser el más constante, RLR",
  "Hoy me hablo como me hablaría un buen entrenador: directo, exigente y compasivo, RLR",
  "La voz que me dice “no puedes” lleva años hablando; hoy le bajo el volumen, no la apago, RLR",
  "Cuando me equivoco, no me bajo del juego, solo aprendo del jugador, RLR",
  "La confianza profunda no necesita aplausos para sostenerse, RLR",
  "Hoy honro la versión de mí que se atrevió, aunque hoy todavía no se note el resultado, RLR",
  "Lo que parecía ego, a veces era solo confianza disfrazada porque nadie me había enseñado a llamarlo así, RLR",
  "La humildad y la confianza no son opuestos; son las dos manos del mismo cuerpo, RLR",
  "Hoy reviso mis “victorias secretas”: las que solo yo sé que conseguí, RLR",
  "Lo que admiro en otros casi siempre es semilla de lo que también tengo, RLR",
  "La confianza se construye haciendo lo que dije que iba a hacer, sobre todo cuando nadie está mirando, RLR",
  "Hoy honro un compromiso pequeño conmigo mismo solo por el placer de cumplirlo, RLR",
  "Mi peor enemigo en la cabeza también puede ser mi mejor aliado si lo educo, RLR",
  "La autocrítica saludable corrige; la autocrítica cruel paraliza. Hoy elijo la primera, RLR",
  "Confío en mi instinto cuando lleva años hablándome bajito sobre lo mismo, RLR",
  "Mi cuerpo sabe antes que mi cabeza; hoy lo escucho un poco más, RLR",
  "La duda persistente sobre algo casi siempre es información, no debilidad, RLR",
  "Hoy reconozco una limitación mía sin convertirla en una sentencia, RLR",
  "Me caigo, me sacudo, me río un poco y sigo: ese también es un superpoder, RLR",
  "La confianza profunda es saber que puedo empezar de nuevo cuantas veces sea necesario, RLR",
  "Hoy le agradezco al miedo, porque me hizo prepararme bien, RLR",
  "Soy mi propio testigo principal; nadie va a creerme antes que yo, RLR",
  "Cierro el mes con una confianza más callada y más firme, RLR",
  "La sabiduría no se nota en lo que digo, se nota en lo que dejo de decir, RLR",
  "El que mucho sabe casi siempre habla poco; el que poco sabe casi siempre habla mucho, RLR",
  "Hoy escucho a alguien sin querer dar consejos no pedidos, RLR",
  "La pregunta correcta abre más mundos que la respuesta correcta, RLR",
  "Aprendo más de lo que no entiendo del todo que de lo que ya domino, RLR",
  "Hoy estoy dispuesto a estar equivocado y eso ya es libertad, RLR",
  "Los maestros buenos también dudan, solo que dudan en privado, RLR",
  "Releo lo que ya sé como si fuera nuevo, y casi siempre me sorprende, RLR",
  "Hoy busco contradicciones en mis propias ideas, porque ahí casi siempre está mi siguiente lección, RLR",
  "La intuición es conocimiento que el cuerpo procesó antes que la mente, RLR",
  "Hoy honro una corazonada en lugar de pedirle pruebas, RLR",
  "La sabiduría no es acumular información, es saber qué información ignorar, RLR",
  "Lo que se entiende rápido casi siempre se entiende superficial; lo que toma años se entiende profundo, RLR",
  "Hoy le doy tiempo a una idea para que madure dentro de mí antes de actuar sobre ella, RLR",
  "El silencio es donde las ideas se vuelven verdades vividas, RLR",
  "No todo lo que pienso vale la pena decirlo; algunos pensamientos solo me pertenecen a mí, RLR",
  "Hoy guardo un secreto bonito sobre mí mismo, sin necesidad de presumirlo, RLR",
  "El consejo que doy debería ser el consejo que yo mismo cumplo, RLR",
  "Hoy me pregunto: ¿esto que voy a decir mejora el silencio, RLR",
  "Lo más profundo que sé probablemente lo aprendí en una situación muy simple, RLR",
  "Los libros buenos confirman lo que mi cuerpo ya sospechaba, RLR",
  "La verdad sencilla casi siempre vence a la verdad complicada, RLR",
  "Hoy me callo cuando no es mi turno, aunque tenga algo bueno que decir, RLR",
  "Saber cuándo no hablar es la forma más fina de inteligencia social, RLR",
  "Mi vida es mi maestra principal; los libros solo son notas al margen, RLR",
  "Hoy honro a alguien mayor que yo escuchándolo de verdad, RLR",
  "La sabiduría llega cuando dejo de querer tener la razón a toda costa, RLR",
  "Aprendo más de mis errores compartidos que de mis aciertos presumidos, RLR",
  "Hoy escribo una página solo para mí, sin pensar en publicarla, RLR",
  "Cierro abril con menos opiniones y más certezas en silencio, RLR",
  "El servicio que cobra aplauso casi nunca es servicio, es transacción, RLR",
  "Hoy ayudo a alguien sin que nadie sepa que fui yo, RLR",
  "La generosidad anónima es la que más cambia al que la da, RLR",
  "Servir bien es resolver el problema antes de que el otro tenga que pedirlo, RLR",
  "Hoy noto qué necesita la gente a mi alrededor sin esperar que me lo digan, RLR",
  "El servicio verdadero no espera “gracias”; recibirlo es un bono, no el pago, RLR",
  "Mi trabajo, aunque parezca pequeño, es parte de algo más grande que no veo, RLR",
  "Hoy hago bien algo aburrido, solo porque le va a tocar a alguien después, RLR",
  "La excelencia silenciosa es una forma de oración, RLR",
  "Cuido los detalles que nadie revisa; ahí se nota mi carácter, RLR",
  "Hoy dejo un lugar más limpio de como lo encontré, RLR",
  "Servir es tratar al de hasta abajo igual de bien que al de hasta arriba, RLR",
  "Mi sonrisa con el cajero, el guardia o la persona que limpia cuenta lo mismo que con mi jefe, RLR",
  "Hoy aprendo el nombre de alguien al que veo seguido y nunca le había preguntado, RLR",
  "La forma en que trato a quien no puede devolverme nada dice todo de mí, RLR",
  "Servir es bajar la cabeza para que el otro pueda ver más alto, RLR",
  "Hoy le hago la vida más fácil a alguien sin presumirlo, RLR",
  "La gente recuerda cómo la hice sentir, mucho más que lo que le dije, RLR",
  "Hoy doy las gracias a tres personas a las que rara vez se las doy, RLR",
  "Servir no me hace pequeño, me hace ancho, RLR",
  "La verdadera autoridad no se impone, se reconoce, RLR",
  "Hoy ofrezco lo que sé sin condicionar a quién se lo doy, RLR",
  "Mi tiempo regalado a alguien que lo necesita vale más que cualquier transferencia, RLR",
  "Hoy escucho a alguien sin interrumpirlo ni una sola vez, RLR",
  "El servicio bien hecho es invisible: solo se nota cuando falta, RLR",
  "Hoy enseño a alguien algo que sé, sin sentirme amenazado por que aprenda, RLR",
  "Mi mejor herencia no es lo que dejo, es a quien dejo mejor, RLR",
  "Hoy bendigo en silencio a las personas con las que me cruzo en la calle, RLR",
  "La generosidad genuina no nace de tener mucho, nace de no tener miedo, RLR",
  "Hoy entrego algo que no estaba seguro de querer soltar, porque alguien lo necesita más, RLR",
  "Cierro mayo con manos más abiertas y corazón más ancho, RLR",
  "El amor maduro no necesita repetirse para confirmarse, RLR",
  "Hoy quiero a alguien con hechos pequeños en lugar de palabras grandes, RLR",
  "Amar es dejar al otro ser sin tener que entenderlo del todo, RLR",
  "La presencia silenciosa al lado de alguien es una forma muy alta de cariño, RLR",
  "Hoy estoy con mi gente sin agenda, sin teléfono, sin razón, RLR",
  "El amor que aprieta no es amor, es miedo disfrazado, RLR",
  "Hoy le doy a alguien permiso de no estar bien, sin querer arreglarlo, RLR",
  "Quien me ama de verdad me deja crecer, aunque crezca lejos, RLR",
  "El amor verdadero no compite, suma, RLR",
  "Hoy honro a alguien aceptando una decisión suya que yo hubiera tomado distinto, RLR",
  "Las relaciones que duran no son las que no tienen problemas, son las que saben repararse, RLR",
  "Hoy reparo algo pequeño con alguien, sin esperar que él dé el primer paso, RLR",
  "El amor sin admiración se enfría; hoy le digo a alguien qué admiro de él, RLR",
  "Las palabras suaves no son debilidad, son maestría, RLR",
  "Hoy elijo creer lo mejor de alguien antes de creer lo peor, RLR",
  "El amor incondicional no es aguantar todo; es no condicionar el cariño al comportamiento, RLR",
  "Hoy abrazo a alguien tres segundos más de lo necesario, RLR",
  "Lo que más le agradezco a las personas que amo es haberme aguantado mientras crecía, RLR",
  "Hoy le digo a un amigo lo que significa para mí, sin esperar a su cumpleaños o su funeral, RLR",
  "La gente que más me reta también es la que más me forma, RLR",
  "Hoy bendigo a alguien con quien estoy enojado, no por ellos, por mí, RLR",
  "El amor propio es el cimiento; sin él, lo que doy a otros es necesidad disfrazada, RLR",
  "Hoy me trato con la ternura con la que trataría a un hijo asustado, RLR",
  "Las heridas viejas duelen menos cuando dejo de fingir que no existen, RLR",
  "Hoy reconozco una herida sin convertirla en mi identidad, RLR",
  "Mi capacidad de amar crece cada vez que perdono algo grande, RLR",
  "La distancia con alguien a veces es la forma más amorosa de seguir queriéndolo, RLR",
  "Hoy elijo el amor maduro: el que respeta, no el que asfixia, RLR",
  "Querer es desear el bien del otro, aunque ese bien me incluya menos, RLR",
  "Cierro junio con relaciones más limpias y más verdaderas, RLR",
  "Mi cuerpo es el primer hogar que tuve y será el último; hoy le hablo bonito, RLR",
  "El cuerpo no miente; lo que la mente niega, el cuerpo lo guarda, RLR",
  "Hoy noto qué siento físicamente antes de saber qué pienso, RLR",
  "Una tensión en los hombros casi siempre es una palabra que no dije, RLR",
  "Hoy suspiro tres veces, profundo, sin razón aparente, y mi cuerpo me lo agradece, RLR",
  "Mi cuerpo me lleva más lejos cuando lo trato como aliado y no como caballo, RLR",
  "Lo que como hoy, mi cuerpo lo construye o lo combate; no hay neutro, RLR",
  "Hoy mastico despacio una sola comida; eso es meditación disfrazada, RLR",
  "Mi cuerpo recuerda lo que mi mente no quiere recordar; ahí están las claves, RLR",
  "Una hora de sueño antes de medianoche vale dos después de medianoche, RLR",
  "Hoy honro mi cansancio en lugar de pelearme con él, RLR",
  "El descanso real no es no hacer nada, es hacer cosas distintas a las que me agotan, RLR",
  "Mi cuerpo me pide silencio antes de pedirme medicina, RLR",
  "Hoy camino sin rumbo unos minutos, solo para que mi cuerpo respire, RLR",
  "El sol en la piel diez minutos hace lo que muchos suplementos prometen, RLR",
  "Hoy me siento derecho, hombros atrás, y noto cómo cambia mi ánimo, RLR",
  "Mi respiración es el control remoto del sistema nervioso, y es gratis, RLR",
  "Cuatro respiraciones largas pueden bajarle el volumen a la ansiedad más rápido que cualquier otro truco, RLR",
  "Hoy bostezo a propósito, porque el bostezo es una pequeña liberación, RLR",
  "Mi cuerpo lleva años cuidándome; le debo más respeto del que le doy, RLR",
  "Hoy me doy un baño largo sin sentirme culpable por el tiempo, RLR",
  "La piel también necesita cariño consciente; hoy la toco como tocaría a alguien amado, RLR",
  "Mi cuerpo me pide movimiento, no perfección, RLR",
  "Hoy estiro lo que duela; ahí casi siempre está la información, RLR",
  "La gratitud bajada al cuerpo se vuelve sonrisa, hombros sueltos, paso suave, RLR",
  "Hoy abrazo mi cuerpo tal como está, sin esperar a que cambie para apreciarlo, RLR",
  "El placer simple — comer, dormir, abrazar, reírme — es medicina seria, RLR",
  "Hoy me doy permiso de disfrutar mi cuerpo en lugar de evaluarlo, RLR",
  "La salud no es una meta a alcanzar; es una conversación diaria con mi cuerpo, RLR",
  "Mi cuerpo es prestado, no comprado; hoy lo cuido con esa conciencia, RLR",
  "Cierro julio prometiéndome menos juicio y más escucha, RLR",
  "El silencio no es el enemigo del pensamiento; es donde el pensamiento bueno aparece, RLR",
  "Hoy paso cinco minutos sin decir, oír ni leer nada, solo respirando, RLR",
  "La ansiedad odia el silencio bien sostenido; ahí pierde su voz, RLR",
  "Hoy apago la música en el coche unos kilómetros, y dejo que mi cabeza hable sola, RLR",
  "El aburrimiento es la antesala de la creatividad; hoy lo aguanto en lugar de huirle, RLR",
  "Mi mente vacía no es perezosa, es fértil, está esperando algo bueno, RLR",
  "Hoy no contesto un mensaje urgente por veinte minutos, y descubro que no era tan urgente, RLR",
  "La urgencia constante es una mentira que el mundo se cuenta entre sí, RLR",
  "Hoy hago menos cosas y las disfruto más; no hay premio por estar ocupado, RLR",
  "Estar ocupado no es lo mismo que estar siendo útil, RLR",
  "Hoy reconozco que llenar el día de actividades a veces es huir de mí mismo, RLR",
  "El vacío bien habitado es el suelo de toda creación, RLR",
  "Hoy me siento un rato sin agenda y veo qué emerge, RLR",
  "La meditación no es vaciar la mente, es no creerle todo a la mente, RLR",
  "Hoy observo un pensamiento sin tomarme nada personal con él, RLR",
  "Mis pensamientos pasan por mi cabeza como nubes; yo soy el cielo, no las nubes, RLR",
  "Hoy me río un poco de mis pensamientos catastróficos, RLR",
  "La mente quiere problemas; cuando no encuentra, los inventa. Hoy no le doy material, RLR",
  "El silencio interior se entrena, no se encuentra, RLR",
  "Hoy le doy permiso a mi mente de no resolver nada por una hora, RLR",
  "La paz no es una recompensa; es mi estado por defecto cuando dejo de agitar, RLR",
  "Hoy elijo no opinar sobre algo, aunque pueda, RLR",
  "Lo que callo crece distinto a lo que digo; hoy callo lo justo, RLR",
  "La ansiedad es energía sin canal; hoy le abro un canal: caminar, escribir, respirar, RLR",
  "Hoy no resuelvo el problema que me preocupa; solo respiro y lo dejo descansar también, RLR",
  "Lo que me preocupa por la noche casi siempre se ve diferente por la mañana, RLR",
  "Hoy le pongo nombre a lo que siento, en voz baja, y eso solo ya lo ablanda, RLR",
  "Mi sistema nervioso se calma cuando dejo de actuar como si todo fuera emergencia, RLR",
  "Hoy hablo más despacio y noto cómo todo a mi alrededor se desacelera también, RLR",
  "La quietud es el canal donde llegan las ideas que de verdad valen, RLR",
  "Cierro agosto sabiendo que el silencio bien usado es mi mejor aliado, RLR",
  "Creo lo que tengo que crear y lo entrego al mundo sin pedirle nada a cambio, RLR",
  "Mi obra no me pertenece una vez que sale de mí; pertenece a quien la necesita, RLR",
  "Hoy hago algo solo por el gusto de hacerlo, sin necesidad de monetizarlo, RLR",
  "Crear sin agarrar es crear desde la abundancia, RLR",
  "Hoy publico algo aunque no esté perfecto, porque perfecto es excusa para nunca, RLR",
  "Lo que tarda demasiado en salir, casi siempre se infla en el camino, RLR",
  "Hoy termino el primer borrador y le quito los detalles después, RLR",
  "La creatividad no se acaba; lo que se acaba es la energía de quien no descansa, RLR",
  "Mi mejor trabajo no será el que más planeo; será el que más fluya, RLR",
  "Hoy creo desde el juego, no desde la obligación, RLR",
  "La obra de arte más profunda casi siempre se hizo sin saber qué iba a salir, RLR",
  "Hoy confío en el proceso aunque no vea el final, RLR",
  "Lo que creo me revela; no creo para agradar, creo para conocerme, RLR",
  "Hoy hago algo que solo a mí me importa; eso ya lo justifica, RLR",
  "Crear es decir “yo estuve aquí” sin necesidad de gritarlo, RLR",
  "Mi voz importa, aunque haya millones diciendo cosas parecidas, porque la mía es la mía, RLR",
  "Hoy escribo, dibujo o construyo algo que llevo postergando hace meses, RLR",
  "La originalidad no es no parecerse a nadie; es parecerse profundamente a uno mismo, RLR",
  "Hoy copio descaradamente lo que admiro, sabiendo que pasándolo por mí ya se transforma, RLR",
  "Las ideas que no aterrizan se mueren con uno; hoy aterrizo una, RLR",
  "Crear con lo que tengo, donde estoy, ahora, es mil veces mejor que esperar el momento ideal, RLR",
  "Hoy uso una herramienta nueva sin pedirle permiso a mi inseguridad, RLR",
  "La inteligencia artificial es lápiz nuevo; lo importante sigue siendo lo que tengo que decir, RLR",
  "Hoy le pido ayuda a alguien con algo que solo yo no podría terminar, RLR",
  "Crear en comunidad multiplica; crear en solitario profundiza. Hoy elijo el que toca, RLR",
  "Lo que hago hoy podría servirle a alguien dentro de cien años; eso es suficiente motivo, RLR",
  "Hoy le pongo fecha a un proyecto que vivía en “algún día”, RLR",
  "La creación honesta cura más al que la hace que al que la recibe, RLR",
  "Hoy creo algo y lo regalo, solo para acordarme de que no creo por dinero, RLR",
  "Cierro septiembre con una obra más fuera de mí, lista para vivir su propia vida, RLR",
  "Ver claro es ver lo que es, no lo que quisiera que fuera, RLR",
  "Hoy nombro algo por su nombre real, aunque me incomode, RLR",
  "La claridad duele al principio y libera después, RLR",
  "Lo que niego me controla; lo que reconozco lo puedo trabajar, RLR",
  "Hoy admito una verdad pequeña sobre mí, en privado, y eso ya me alivia, RLR",
  "Las mentiras que me cuento a mí mismo son las más caras de todas, RLR",
  "Hoy reviso una creencia heredada y veo si todavía me sirve, RLR",
  "No todo lo que pienso es mío; mucho lo absorbí sin elegirlo, RLR",
  "Hoy distingo entre mis voces propias y las voces que me tragué de afuera, RLR",
  "Ver claro es renunciar a la versión cómoda de la historia, RLR",
  "Lo que veo de los demás casi siempre dice algo de mí también, RLR",
  "Hoy me pregunto qué me molesta de alguien y reviso si yo también lo hago, RLR",
  "La proyección es un espejo; hoy lo limpio, RLR",
  "Veo claro cuando dejo de querer tener la razón sobre lo que pasó, RLR",
  "Hoy reconozco mi parte en un conflicto, sin dejar de ver la del otro, RLR",
  "La madurez es poder sostener dos verdades opuestas sin colapsar, RLR",
  "Hoy acepto que algo es bueno y malo al mismo tiempo, y no pasa nada, RLR",
  "La realidad es más compleja que mis etiquetas; hoy las uso menos, RLR",
  "Hoy escucho una opinión opuesta a la mía sin necesidad de derrotarla, RLR",
  "Cambiar de opinión cuando aparece mejor información es signo de inteligencia, no de debilidad, RLR",
  "Ver claro es ver el sistema, no solo a la persona, RLR",
  "Hoy entiendo que muchos de los que me hicieron daño también estaban heridos, RLR",
  "Entender no es justificar; es ampliar el ángulo, RLR",
  "La compasión empieza cuando veo que el otro hace lo que puede con lo que tiene, RLR",
  "Hoy me veo con la misma compasión con la que vería a otro, RLR",
  "Ver claro mi pasado es la única forma de no repetirlo, RLR",
  "Hoy reconozco un patrón mío y le pongo nombre, RLR",
  "La verdad simple es: no soy especial en mis defectos, son humanos. Y tampoco en mis virtudes; también son humanas, RLR",
  "Hoy me río de algo de mí que antes me avergonzaba, RLR",
  "Ver claro es la base de todo cambio real, RLR",
  "Cierro octubre con menos máscaras y más cara propia, RLR",
  "No soy mi historia; soy quien la cuenta, RLR",
  "Hoy suelto una etiqueta que llevo años cargando como si fuera mía, RLR",
  "Lo que dije que era hace cinco años no tiene por qué definirme hoy, RLR",
  "Soy más grande que cualquier rol que ocupe, RLR",
  "Hoy decido no ser solo “papá”, “hijo”, “jefe”, “empleado”; soy alguien que también juega esos papeles, RLR",
  "Mi profesión es lo que hago, no lo que soy, RLR",
  "Hoy hago algo completamente fuera de mi “personaje”, solo para acordarme, RLR",
  "Las personalidades fuertes a veces son cárceles bonitas, RLR",
  "Hoy me doy permiso de ser distinto a como me conocen, RLR",
  "Cambiar no es traicionar quien fui; es honrar quien estoy siendo, RLR",
  "La gente se incomoda cuando cambio porque cuestiona la versión que también eligieron de sí mismos, RLR",
  "Hoy decepciono cariñosamente a alguien que esperaba la versión vieja de mí, RLR",
  "Soltar la imagen que tengo de mí es soltar mi prisión más íntima, RLR",
  "Hoy me pregunto: si nadie supiera quién soy, ¿qué haría hoy distinto, RLR",
  "Mi ego no es enemigo; es un asistente al que a veces le doy demasiado poder, RLR",
  "Hoy le agradezco a mi ego lo que me cuidó, y le pido que se haga a un lado para ciertas cosas, RLR",
  "Lo que más me cuesta soltar suele ser lo que más necesito soltar, RLR",
  "Hoy suelto una opinión que me costó mucho construir, porque ya no me sirve, RLR",
  "Soltar es saber que detrás de lo que suelto hay algo más espacioso esperando, RLR",
  "Hoy hago algo en silencio, sin contarle a nadie, solo por el placer de hacerlo, RLR",
  "No tengo que ser coherente con mi pasado; tengo que ser coherente con mi presente, RLR",
  "Las contradicciones no son defectos; son señales de que estoy creciendo, RLR",
  "Hoy reconozco una contradicción mía sin esconderla, RLR",
  "La autenticidad es ser fiel al cambio, no a la imagen, RLR",
  "Hoy me presento a un día sin guion ni personaje preparado, RLR",
  "Quitarme una máscara cansa al principio y libera después, RLR",
  "Hoy nombro algo que pretendo que no me importa pero sí me importa, RLR",
  "La verdad simple casi siempre era lo que estaba evitando, RLR",
  "Hoy honro al yo que está naciendo, sin juzgar al yo que se está yendo, RLR",
  "Cierro noviembre más yo y menos personaje, RLR",
  "Lo sagrado no está lejos; está aquí, esperando que lo reconozca, RLR",
  "Hoy lavo los platos como si fuera lo más importante del mundo, porque por veinte minutos lo es, RLR",
  "La rutina no es enemiga del despertar; es donde se vive el despertar, RLR",
  "Hoy hago una cosa simple con toda mi atención, y eso ya es meditación, RLR",
  "La vida no espera el momento “importante”; es importante todo el tiempo, RLR",
  "Hoy noto la luz que entra por la ventana, como si fuera la primera vez, RLR",
  "Lo eterno se asoma en los detalles que uno casi no nota, RLR",
  "Hoy le doy las gracias a mi taza de café, no por superstición, por costumbre buena, RLR",
  "Mi vida no va a empezar cuando logre algo; mi vida es esto que está pasando, RLR",
  "Hoy estoy completo, exactamente como estoy, aunque me falten cosas, RLR",
  "La búsqueda eterna a veces es ruido; lo que busco ya estaba aquí, RLR",
  "Hoy paro de perseguir y empiezo a recibir, RLR",
  "Lo cotidiano repetido con conciencia se vuelve sagrado, RLR",
  "Hoy hago una caminata corta como si fuera peregrinación, RLR",
  "La paz no llegó como creí que llegaría; llegó callada, en una tarde común, RLR",
  "Hoy reconozco un momento ordinario y lo guardo en mi memoria como tesoro, RLR",
  "Las grandes vidas se viven en los espacios entre los grandes momentos, RLR",
  "Hoy bendigo el tráfico, la fila, la espera, porque también son mi vida, RLR",
  "Lo que parece pérdida de tiempo a veces es donde la vida más me habla, RLR",
  "Hoy escucho a un niño decir algo y le presto atención de verdad, RLR",
  "La sabiduría se asoma en las personas más simples, si las dejo, RLR",
  "Hoy descubro algo profundo en una conversación con un desconocido, RLR",
  "La eternidad cabe en un instante presente bien habitado, RLR",
  "Hoy estoy donde estoy, sin querer estar en otro lado, ni siquiera por un segundo, RLR",
  "La gratitud por estar vivo no necesita ocasión especial; hoy es ocasión, RLR",
  "El milagro de respirar es tan común que se me olvida; hoy me acuerdo, RLR",
  "Hoy me detengo a ver una flor, una nube, un árbol, sin urgencia, RLR",
  "La vida me hace señales todo el tiempo; hoy estoy disponible para verlas, RLR",
  "Lo que me sobra al final del día es el regalo verdadero, RLR",
  "Hoy bendigo este año, este día, este minuto, este aliento, RLR",
  "Cierro este segundo año con más reverencia y menos ruido, RLR",
  "La gratitud más profunda no agradece algo; agradece todo, sin objeto, RLR",
  "Hoy doy las gracias sin razón, solo porque sí, y eso me cambia el día, RLR",
  "La gratitud sin condiciones es la única que dura, RLR",
  "Si solo agradezco lo bueno, mi gratitud es turista; cuando agradezco lo difícil, es habitante, RLR",
  "Hoy agradezco aquello que todavía no entiendo por qué me está pasando, RLR",
  "La vida no me debe nada y, aun así, me da todo, RLR",
  "Hoy agradezco haber sido niño, joven, adulto, y la suerte de seguir cambiando, RLR",
  "La gratitud verdadera no es una emoción; es un eje, RLR",
  "Hoy doy las gracias por mi historia, sin querer reescribirla, RLR",
  "La gratitud por la propia vida es la gratitud que cura todas las demás, RLR",
  "Hoy agradezco poder agradecer; no todos pueden, no todos quieren, RLR",
  "La gratitud profunda es saber que no me toca todo, y que con lo que me toca, sobra, RLR",
  "Doy las gracias por el aire que entra y por el aire que sale; los dos son regalos, RLR",
  "Hoy agradezco no haber recibido lo que pedí cuando lo pedí, RLR",
  "La gratitud sin objeto es una forma de oración para los que ya no creen en oraciones, RLR",
  "Hoy agradezco a la vida en abstracto, sin destinatario, RLR",
  "La gratitud más alta es por la conciencia misma, por estar siendo, RLR",
  "Doy las gracias por todo lo que está pasando ahora mismo en mi cuerpo sin que yo lo dirija, RLR",
  "Hoy agradezco la posibilidad de cambiar; eso solo ya es regalo, RLR",
  "Cuando no encuentro nada por qué dar gracias, doy gracias por la búsqueda misma, RLR",
  "La gratitud convierte el “tengo que” en “tengo el privilegio de”, RLR",
  "Hoy cambio “tengo que ir a trabajar” por “tengo el privilegio de tener trabajo”, RLR",
  "La gratitud reescribe el día sin cambiarle nada, RLR",
  "Hoy agradezco a quien todavía no he conocido, pero pronto va a entrar a mi vida, RLR",
  "La gratitud anticipada es fe en su forma más práctica, RLR",
  "Hoy doy las gracias por algo que todavía no llega y que ya siento que viene, RLR",
  "La gratitud no necesita motivos; los motivos solo confirman lo que la gratitud ya sabía, RLR",
  "Hoy estoy agradecido sin necesidad de explicárselo a nadie, RLR",
  "La gratitud, llevada al extremo, se convierte en silencio, RLR",
  "Doy las gracias incluso por los momentos que no quería que pasaran, RLR",
  "Cierro enero más liviano: la gratitud es el equipaje que pesa menos, RLR",
  "Las cosas más importantes que hago no las “hago”; pasan a través de mí, RLR",
  "Hoy actúo sin sentir que soy “el que actúa”, RLR",
  "El esfuerzo sin tensión rinde más que el esfuerzo con tensión, RLR",
  "Hago como respiro: sin pensar tanto, con confianza, RLR",
  "Hoy dejo de “esforzarme” y empiezo a estar presente en lo que hago, RLR",
  "La acción correcta no se siente como pelear; se siente como caer en su sitio, RLR",
  "Hoy noto cuándo estoy actuando desde el miedo y cuándo desde el flujo, RLR",
  "Lo que fluye no se cansa; lo que se fuerza siempre se cansa, RLR",
  "Hoy hago menos pero entrego más, RLR",
  "La efectividad real no es hacer mucho; es hacer lo que importa, RLR",
  "Hoy decido no hacer una cosa que iba a hacer, y eso ya es trabajo, RLR",
  "La pereza inteligente es elegir qué no hacer; la pereza tonta es no elegir, RLR",
  "El que más rinde no es el que más se mueve; es el que se mueve mejor, RLR",
  "Hoy trabajo en algo y me olvido del tiempo; eso es señal de que voy bien, RLR",
  "El flujo es el premio del que se preparó suficiente para soltar el control, RLR",
  "Hoy preparo bien y luego suelto, RLR",
  "Hacer sin hacer no es flojera; es economía profunda, RLR",
  "La sabiduría es saber cuándo empujar y cuándo esperar, RLR",
  "Hoy espero, sin que la espera me ponga nervioso, RLR",
  "El árbol no se apura para crecer; yo tampoco debería, RLR",
  "Hoy hago lo que me toca y me retiro a tiempo, RLR",
  "La huella se nota más cuando se siente menos esfuerzo, RLR",
  "Hoy dejo que algo se cocine solo, sin estar revisándolo cada minuto, RLR",
  "La paciencia es la otra cara del trabajo bien hecho, RLR",
  "Hoy elijo terminar bien una cosa antes que avanzar mal en cinco, RLR",
  "El “no hacer” sabio es el que más se nota cuando no estoy, RLR",
  "Hoy delego algo, no por flojera, sino por confianza, RLR",
  "Cierro febrero con manos cansadas pero corazón descansado, RLR",
  "Soy más de lo que pienso y menos importante de lo que mi ego cree, RLR",
  "Hoy bajo el volumen de mi “yo” y subo el de la vida, RLR",
  "Mi “yo” no es enemigo; es un personaje útil al que a veces le doy demasiada línea, RLR",
  "Hoy me observo sin identificarme con todo lo que observo, RLR",
  "El “yo” que sufre y el “yo” que observa al que sufre no son el mismo, RLR",
  "Hoy practico ser el observador en lugar del observado, RLR",
  "Lo que cambia en mí no soy yo; yo soy lo que se mantiene, RLR",
  "Detrás de mis pensamientos hay alguien que los nota: ese soy yo, más yo, RLR",
  "Hoy me siento callado un rato y noto quién está detrás de mis ojos, RLR",
  "La identidad sólida es una ilusión útil; la identidad fluida es más cierta, RLR",
  "Soy distinto al de hace diez años, y sin embargo soy el mismo, RLR",
  "Hoy me reconcilio con todas las versiones que he sido, RLR",
  "No tengo que elegir entre ser firme y ser flexible; soy las dos cosas, RLR",
  "Hoy me dejo ser todo lo que soy, sin necesidad de unificarlo en una marca, RLR",
  "Mi nombre es un sonido; lo que soy es más antiguo, RLR",
  "Hoy uso menos la palabra “soy” para definirme rígidamente, RLR",
  "Cambio “soy ansioso” por “estoy con ansiedad ahora”, y eso me alivia, RLR",
  "Cambio “soy desordenado” por “ahora estoy practicando orden”, y eso me empuja, RLR",
  "Mis estados no son mi esencia; pasan por mí, no son yo, RLR",
  "Hoy reconozco una emoción sin convertirme en ella, RLR",
  "La rabia me visita; yo no soy la rabia, RLR",
  "La tristeza pasa por mí; yo no soy la tristeza, RLR",
  "La alegría también pasa; tampoco soy la alegría, RLR",
  "Lo que en mí no pasa es lo que de verdad soy, RLR",
  "Hoy me siento detrás de mis emociones, las saludo y las dejo seguir su camino, RLR",
  "No soy lo que tengo, no soy lo que hago, no soy lo que digo; soy lo que queda cuando todo eso se silencia, RLR",
  "Hoy me callo lo suficiente para escuchar quién soy de verdad, RLR",
  "La libertad más profunda es saber que no necesito ser nadie en particular, RLR",
  "Hoy soy menos “alguien” y más “algo siendo”, RLR",
  "Soy una conciencia tomando forma humana por un rato; lo respeto, RLR",
  "Cierro marzo con menos identidad y más presencia, RLR",
  "Lo más importante que sé no lo aprendí en libros, RLR",
  "Hoy confío en lo que sé sin poder explicarlo, RLR",
  "La inteligencia analítica me sirve hasta cierto punto; después necesito otra inteligencia, RLR",
  "El cuerpo sabe; las emociones saben; el silencio sabe, RLR",
  "Hoy le pregunto algo a mi cuerpo y le doy treinta segundos de respuesta, RLR",
  "La intuición es la sabiduría que no necesita pasar por palabras, RLR",
  "Hoy honro una decisión sin tener una explicación racional para ella, RLR",
  "Saber sin saber es permitirme reconocer lo que ya está claro adentro, RLR",
  "La duda mental constante a veces es solo evasión de saber, RLR",
  "Hoy admito que ya sabía algo, mucho antes de aceptarlo, RLR",
  "Lo que más me cuesta no es aprender; es desaprender, RLR",
  "Hoy desaprendo una creencia sobre mí que ya no me sirve, RLR",
  "El conocimiento real cambia mi vida; el resto es trivia, RLR",
  "Hoy aplico una sola cosa que ya sé pero no estaba haciendo, RLR",
  "Saber y no aplicar es no saber, RLR",
  "La sabiduría no se acumula como datos; se decanta como vino, RLR",
  "Hoy le doy tiempo a una idea para que decante en mí, RLR",
  "Lo simple aprendido a fondo vale más que lo complejo aprendido a medias, RLR",
  "La vida me enseña con repetición lo que no entendí la primera vez, RLR",
  "Hoy reviso si una situación que se repite me está enseñando algo, RLR",
  "Mi cuerpo me lo había dicho hace meses; hoy le hago caso, RLR",
  "La sabiduría profunda muchas veces se siente como sentido común tardío, RLR",
  "Hoy honro una corazonada sin pedirle pruebas a la corazonada, RLR",
  "La intuición se atrofia cuando no la uso; hoy la uso aunque sea en algo pequeño, RLR",
  "Hoy decido algo desde el cuerpo, no desde el cálculo, RLR",
  "Lo que ya sé probablemente alcanza; me falta confianza para usarlo, RLR",
  "La vida no me pide más conocimiento; me pide más coraje para aplicar el que tengo, RLR",
  "Hoy aplico, aplico, aplico, y guardo el aprender para después, RLR",
  "Saber sin saber es la confianza de un cuerpo que ha vivido suficiente, RLR",
  "Cierro abril con más certezas calladas y menos opiniones ruidosas, RLR",
  "Cuando doy bien, recibo en el acto; no después, en el mismo segundo, RLR",
  "La generosidad no me empobrece; me revela cuánto cabía en mí, RLR",
  "Hoy doy algo y noto qué se mueve en mí al darlo, RLR",
  "Dar bien es una forma de recibir paz, RLR",
  "Hoy regalo tiempo, que es lo único que de verdad no se devuelve, RLR",
  "La avaricia es un agujero sin fondo; la generosidad es un círculo cerrado de bien, RLR",
  "Hoy honro a alguien aceptando lo que me ofrece, en lugar de rechazar por orgullo, RLR",
  "Recibir bien es tan importante como dar bien, RLR",
  "Hoy digo “gracias” a un regalo sin minimizarlo ni devolverlo de inmediato, RLR",
  "La incapacidad de recibir es una forma sutil de avaricia, RLR",
  "Hoy dejo que alguien me cuide, sin sentir que lo debo, RLR",
  "El que solo da y nunca recibe se quema; el que solo recibe y nunca da se vacía. El equilibrio cura, RLR",
  "Doy lo mejor que tengo; recibo lo mejor que me llega, RLR",
  "Hoy bendigo lo que recibí sin haberlo pedido, ni planeado, ni merecido, RLR",
  "Lo no merecido es el espacio donde la gracia respira, RLR",
  "La gracia es lo bueno que llega sin haber sido ganado, RLR",
  "Hoy reconozco una gracia en mi vida y no la confundo con suerte, RLR",
  "Servir desde el lleno es bendición; servir desde el vacío es desgaste, RLR",
  "Hoy me lleno antes de salir a dar, RLR",
  "La caridad sostenida en culpa se siente; la caridad sostenida en gratitud, también, RLR",
  "Hoy doy desde la gratitud, no desde la culpa, RLR",
  "Lo que hoy compartí ya regresó; solo todavía no veo cómo, RLR",
  "La economía profunda dice: lo que circula crece, lo que se acumula se queda quieto, RLR",
  "Hoy hago circular algo: dinero, tiempo, conocimiento, cariño, RLR",
  "Mis manos se llenan más cuando se abren que cuando se cierran, RLR",
  "Hoy abro las manos, literal y metafóricamente, RLR",
  "Compartir mi conocimiento no me roba ventaja; me amplía la red, RLR",
  "Hoy enseño algo gratis, y descubro que aprendo el doble, RLR",
  "Recibir bien también es dar: doy a quien dio el placer de haberme dado bien, RLR",
  "Hoy completo un círculo: agradezco a alguien que me dio, sin querer “compensarlo”, RLR",
  "Cierro mayo con un corazón que recibe tan limpio como da, RLR",
  "La vida que palpita en mí es la misma que palpita en cada persona que veo, RLR",
  "Hoy me cuesta menos perdonar cuando recuerdo que el otro y yo somos del mismo material, RLR",
  "Lo que ataco en otro casi siempre es algo que no he integrado en mí, RLR",
  "Hoy busco a alguien al que juzgo, en mí, antes que en él, RLR",
  "La separación es la ilusión más dolorosa, RLR",
  "Hoy noto que estoy unido a mucha más gente de la que reconozco, RLR",
  "La gente que no conozco también está cuidando de mi vida sin saberlo, RLR",
  "Hoy bendigo a quien sembró el café que tomé, a quien manejó el camión, a quien lo vendió, RLR",
  "Mi vida cómoda existe porque miles de personas hacen sus partes sin aplauso, RLR",
  "Hoy reconozco una cadena invisible y le doy las gracias, RLR",
  "La empatía profunda es saber que el otro siente lo mismo que yo en cuerpos parecidos, RLR",
  "Hoy imagino un día en la vida de alguien con quien no me llevo bien, RLR",
  "Detrás de cada conducta dolorosa hay un dolor que pidió ser visto, RLR",
  "Hoy entiendo a alguien aunque no comparta lo que hace, RLR",
  "Entender es ampliar la mirada; no obliga a estar de acuerdo, RLR",
  "La compasión no está reñida con poner límites firmes, RLR",
  "Hoy pongo un límite con cariño, no con desprecio, RLR",
  "La humanidad es una sola conciencia jugando a ser muchas; lo recuerdo cuando me cierro, RLR",
  "Hoy abro un poquito más mi círculo de “los míos”, RLR",
  "El “nosotros” puede ser tan ancho como yo decida, RLR",
  "Mi país, mi gente, mi familia: paso por todos y al final llego a “humanidad”, RLR",
  "Hoy bendigo a personas en otro continente que no conoceré nunca, RLR",
  "Las fronteras se ven en los mapas, no en los corazones, RLR",
  "Hoy hago algo, en pequeño, por alguien fuera de mi círculo cercano, RLR",
  "La vida no me pide salvarla; me pide cuidar mi pedazo bien, RLR",
  "Hoy cuido mi pedazo, y eso ya es contribuir al todo, RLR",
  "Ser útil a uno solo bien vale más que ser inútil a mil, RLR",
  "Hoy concentro mi servicio en una persona, profundo, en lugar de muchas, superficial, RLR",
  "La unidad no se predica, se practica en la cocina, en el trabajo, en el tráfico, RLR",
  "Cierro junio sintiéndome menos solo, aunque a veces esté solo, RLR",
  "Mi cuerpo no es un proyecto a perfeccionar; es un templo a habitar, RLR",
  "Hoy dejo de pelearme con mi cuerpo y empiezo a habitarlo, RLR",
  "La paz con el propio cuerpo es la paz con la propia vida, RLR",
  "Hoy le pido perdón a mi cuerpo por las palabras crueles que le he dicho, RLR",
  "La belleza del cuerpo joven es una; la del cuerpo maduro, otra; ambas son belleza, RLR",
  "Hoy honro las cicatrices, las arrugas, las marcas; cada una es un capítulo, RLR",
  "Mi cuerpo no me debe la imagen que la cultura quiere; me debe llevarme a vivir, RLR",
  "Hoy elijo “fuerte” antes que “delgado”, “ágil” antes que “perfecto”, RLR",
  "La salud es respeto al cuerpo, no obsesión por él, RLR",
  "Cuidar el cuerpo no es vanidad si el motivo es seguir presente para los míos, RLR",
  "Hoy entreno un poco, no por estética, por gratitud, RLR",
  "Mi cuerpo agradece cuando lo muevo y agradece cuando lo descanso; ambos son regalos, RLR",
  "Hoy noto las pequeñas señales de mi cuerpo y las honro antes de que se vuelvan grandes, RLR",
  "La enfermedad casi siempre es lenguaje que ignoré durante años, RLR",
  "Hoy hago una cosa concreta para prevenir, en lugar de reaccionar, RLR",
  "La medicina más efectiva: dormir, moverse, comer real, reírse, abrazarse, RLR",
  "Hoy practico al menos tres de las cinco, RLR",
  "Mi nervio vago se calma con cantar, tararear, suspirar; hoy uso uno, RLR",
  "Tocar la propia piel con cariño manda un mensaje al cerebro: estás a salvo, RLR",
  "Hoy me pongo la mano en el pecho un minuto y respiro, RLR",
  "El cuerpo es donde se vive la vida; sin él, no hay experiencia, RLR",
  "Hoy vivo un placer simple sin culpa, RLR",
  "La sensualidad sana es estar despierto en el cuerpo, no actuar para otros, RLR",
  "Hoy noto un sabor, un olor, un tacto, en lugar de pasarlo de largo, RLR",
  "Mi cuerpo es mi mejor maestro; me enseña en lenguaje que no se puede falsear, RLR",
  "Hoy escucho lo que mi cuerpo lleva tiempo diciendo y yo no quería oír, RLR",
  "La vejez bien llevada es elegancia; el rechazo a envejecer es sufrimiento autoimpuesto, RLR",
  "Hoy acepto que mi cuerpo cambia, y dejo de competir con la versión del año pasado, RLR",
  "Mi cuerpo es prestado por un rato; lo entrego mejor de como lo recibí, RLR",
  "Hoy hago un acto de cuidado por el yo de dentro de veinte años, RLR",
  "Cierro julio en paz con mi templo, RLR",
  "La voz que de verdad importa habla bajo; hoy bajo el volumen del resto, RLR",
  "La quietud no es vacío, es presencia sin distracción, RLR",
  "Hoy me siento quieto cinco minutos, y escucho qué emerge, RLR",
  "El que sabe estar quieto no necesita gran parte de lo que los demás persiguen, RLR",
  "La paz no se persigue, se permite, RLR",
  "Hoy permito un momento de paz, sin condicionarlo a nada, RLR",
  "Lo que es mío no se gana con velocidad; llega cuando estoy listo para recibirlo quieto, RLR",
  "La prisa es ansiedad disfrazada de productividad, RLR",
  "Hoy hago una cosa despacio, a propósito, RLR",
  "La urgencia que siento adentro casi nunca corresponde a una urgencia real afuera, RLR",
  "Hoy distingo entre lo importante y lo urgente; casi nada es ambas, RLR",
  "La quietud expone cosas que la actividad tapaba; hoy las miro sin huir, RLR",
  "La incomodidad bien sostenida se transforma; la incomodidad evitada se queda, RLR",
  "Hoy estoy con una emoción difícil dos minutos más de lo que me gustaría, RLR",
  "Lo que quiere ser visto, una vez visto, se calma, RLR",
  "La ansiedad pierde fuerza cuando dejo de pelearme con ella, RLR",
  "Hoy le digo a mi ansiedad: “te veo, está bien, respiremos juntas”, RLR",
  "La ansiedad es energía; bien dirigida, es combustible, RLR",
  "Hoy canalizo lo que siento en algo: caminar, escribir, llamar, crear, RLR",
  "La quietud no es estar inmóvil; es estar centrado mientras me muevo, RLR",
  "Hoy me muevo desde el centro, no desde la periferia, RLR",
  "La oración silenciosa, sea para quien sea, calma más que las explicaciones, RLR",
  "Hoy guardo silencio cuando podría defenderme, y noto qué pasa, RLR",
  "El que está callado no es el que no tiene argumentos; muchas veces es el que ya no los necesita, RLR",
  "La quietud profunda es saber que estoy a salvo, aunque las cosas no estén resueltas, RLR",
  "Hoy descanso en lo que es, en lugar de empujar lo que debería ser, RLR",
  "Aceptar lo que es no es resignarse; es dejar de gastar energía en lo imposible, RLR",
  "Hoy acepto algo que no me gusta, y descubro que aceptar no lo aprueba, solo lo libera de mi pelea, RLR",
  "La quietud al final del día se construye en los pequeños “no” del día, RLR",
  "Hoy me acuesto sin pendientes mentales rondando, porque ya hice lo que tocaba, RLR",
  "Cierro agosto con menos ruido por dentro que cuando empezó, RLR",
  "Lo que busco casi siempre ya está, solo no lo había visto, RLR",
  "Hoy noto algo bueno que tengo y daba por hecho, RLR",
  "La vida no me debe nuevos regalos; me regaló lo que ya tengo, RLR",
  "Hoy escribo una lista de diez cosas que tengo y muchos no tienen, RLR",
  "La satisfacción no llega cuando consigo más; llega cuando deseo desde otra parte, RLR",
  "Hoy descubro que algo que perseguí ya no me importa tanto, RLR",
  "Madurar es soltar lo que ya no me corresponde, RLR",
  "Hoy revisito un sueño viejo y me pregunto si todavía es mío, RLR",
  "No todos los sueños hay que cumplirlos; algunos sirvieron para ser soñados, RLR",
  "Hoy honro un sueño que solté, sin culpa, RLR",
  "Lo que ya está aquí incluye lo bueno y lo difícil; ambos son la vida, RLR",
  "Hoy abrazo una circunstancia incómoda, no porque me guste, porque es donde estoy, RLR",
  "Resistir lo que es me agota; aceptar lo que es me da fuerza para cambiarlo, RLR",
  "Aceptar no es estar de acuerdo; es dejar de pelearme con la realidad, RLR",
  "Hoy acepto algo que no apruebo, y eso ya me suelta los hombros, RLR",
  "La gratitud por lo que ya hay alimenta lo que viene, RLR",
  "Hoy disfruto, sin remordimiento, algo que ya logré, RLR",
  "Saber recibir lo conseguido es respetar al yo del pasado que se esforzó, RLR",
  "Hoy me felicito por algo del pasado que casi no celebré en su momento, RLR",
  "Mi mejor versión, en parte, ya existe; vive en flashes, en buenos días, en buenos minutos, RLR",
  "Hoy reconozco un momento en el que ya soy quien quiero ser, RLR",
  "Lo que ya está aquí incluye una mente capaz de notar todo esto, RLR",
  "Doy las gracias por la conciencia, sin la cual nada de esto se notaría, RLR",
  "Hoy paso un momento en pura gratitud por estar siendo, RLR",
  "La existencia misma es regalo; el resto, propina, RLR",
  "Hoy me doy cuenta de cuánto he recibido y nunca pedí, RLR",
  "La vida es generosa; mi atención, no siempre, RLR",
  "Hoy ajusto mi atención hacia lo que ya tengo, RLR",
  "Lo que está aquí, ahora, completo, alcanza para ser feliz hoy, RLR",
  "Cierro septiembre sabiendo que la felicidad no viene de afuera, viene de mirar bien lo de adentro, RLR",
  "La vida es perfecta tal como es y, al mismo tiempo, está siempre invitándome a mejorarla, RLR",
  "Hoy sostengo dos verdades opuestas sin tener que elegir, RLR",
  "Lo que es, es; lo que será, será; mi parte está en medio, RLR",
  "Acepto el presente, mejoro lo que puedo, suelto lo que no me toca, RLR",
  "Hoy practico la oración del que entendió: cambia lo que puedas, acepta lo que no puedas, aprende a distinguir, RLR",
  "La paz convive con el deseo de mejorar; no son opuestos, RLR",
  "Hoy busco algo mejor sin rechazar lo presente, RLR",
  "El descontento sano genera movimiento; el descontento crónico genera enfermedad, RLR",
  "Hoy distingo entre los dos, RLR",
  "La perfección no es un lugar; es una dirección, RLR",
  "Hoy doy un paso en la dirección correcta, sin necesidad de llegar, RLR",
  "Lo perfecto, enemigo de lo bueno: hoy elijo bueno y avanzo, RLR",
  "La excelencia es repetir lo bueno hasta que se vuelva natural, RLR",
  "Hoy practico algo a sabiendas de que no me sale aún, y eso ya es maestría empezando, RLR",
  "Lo que parece imperfecto a mí podría ser exactamente lo que otro necesita, RLR",
  "Hoy publico, comparto o entrego algo aunque no esté “perfecto”, RLR",
  "La vida no es lineal; es espiral. Visito los mismos temas más profundo cada vez, RLR",
  "Hoy me reencuentro con un tema viejo y noto cuánto he avanzado, RLR",
  "Lo que hace un año me destrozaba, hoy ya solo me incomoda; ese es progreso, RLR",
  "La verdadera medida no es dónde estoy, es de dónde vengo, RLR",
  "Hoy reviso mi historia y celebro distancia recorrida, RLR",
  "Mejorar no es ser otro; es ser más yo, RLR",
  "Hoy quito una cosa más que me alejaba de mi naturaleza, RLR",
  "La mejora real se ve en cómo respondo, no en cómo me veo, RLR",
  "Hoy respondo distinto a un disparador conocido y eso es transformación, RLR",
  "Lo perfecto y lo perfectible viven juntos; uno no excluye al otro, RLR",
  "Hoy acepto a alguien tal como es y, al mismo tiempo, deseo lo mejor para él, RLR",
  "Aceptación no es rendición; es base para construir bien, RLR",
  "Hoy construyo desde la paz, no desde la queja, RLR",
  "La realidad responde mejor a la aceptación que a la pelea, RLR",
  "Cierro octubre aceptando todo y mejorando algo, RLR",
  "Lo que viví no se pierde; queda hecho yo, RLR",
  "Hoy reconozco una experiencia dolorosa como ladrillo, no como castigo, RLR",
  "Lo que aprendí en mi peor época es lo que hoy uso para servir a otros, RLR",
  "Hoy doy las gracias a un dolor viejo por la persona que me ayudó a ser, RLR",
  "Nada de lo bueno que hice se borra, aunque parezca olvidado, RLR",
  "Mis acciones bien hechas siguen vivas en alguien, aunque yo no me entere, RLR",
  "Hoy hago algo bueno sin necesidad de medir si “rinde”, RLR",
  "El bien hecho no se contabiliza; se acumula en silencio, RLR",
  "Lo que sembré se cosecha, aunque tarde, aunque distinto, aunque otro lo coseche, RLR",
  "Hoy siembro sabiendo que tal vez no veré la cosecha, y aun así siembro, RLR",
  "Las palabras buenas que dije siguen viajando por personas que nunca conoceré, RLR",
  "Hoy elijo palabras que me gustaría que viajaran lejos, RLR",
  "Lo que pierdo en superficie casi siempre lo gano en profundidad, RLR",
  "Hoy agradezco una pérdida que me llevó a algo que no hubiera buscado solo, RLR",
  "Las personas que se fueron de mi vida me dejaron lecciones; eso no se pierde, RLR",
  "Hoy revisito algo que perdí y le encuentro la enseñanza tardía, RLR",
  "El tiempo que pasé equivocado no fue perdido; fue parte del camino, RLR",
  "Hoy me reconcilio con años que creía malgastados, RLR",
  "Cada relación me enseñó algo de mí mismo; nada de eso se borra, RLR",
  "Hoy le agradezco silenciosamente a un ex de cualquier tipo, RLR",
  "Lo que parecía fracaso visto de cerca se ve distinto desde lejos, RLR",
  "Hoy me alejo mentalmente de un fracaso reciente, y le encuentro otro ángulo, RLR",
  "La energía que invertí en algo que no salió, vive en mí como capacidad, RLR",
  "Hoy reconozco una habilidad mía que nació de un proyecto fallido, RLR",
  "Las relaciones interrumpidas a veces dejan más que las completas, RLR",
  "Hoy honro un afecto truncado sin necesidad de revivirlo, RLR",
  "Nada de lo verdadero se pierde; cambia de forma, RLR",
  "Lo que amo nunca se va del todo, aunque se vaya de mi vista, RLR",
  "Hoy llevo conmigo a alguien que ya no está, y me doy cuenta de que sigue presente, RLR",
  "Cierro noviembre sabiendo que mi historia entera es material útil, RLR",
  "Doy las gracias por todo lo que viví, sin escoger solo lo bonito, RLR",
  "Mi historia me trajo aquí, y aquí está bien, RLR",
  "Gracias a lo que dolió, hoy puedo acompañar a otros que duelen, RLR",
  "Hoy abrazo el conjunto, no solo los pedazos que me gustan, RLR",
  "Doy las gracias por las personas que me fallaron, porque también me enseñaron a no fallarme yo, RLR",
  "Hoy bendigo a quien me hirió, no por ellos, por mí, RLR",
  "Lo que rompió mi corazón también amplió su capacidad, RLR",
  "El corazón roto bien curado es más ancho que el corazón intacto, RLR",
  "Hoy honro mis cicatrices, todas, sin pedir disculpas, RLR",
  "Doy las gracias por mis miedos; sin ellos, mi valentía no tendría sentido, RLR",
  "Hoy mi valentía es callada; no la tengo que demostrarle a nadie, RLR",
  "Doy las gracias por las dudas que me hicieron pensar mejor, RLR",
  "Hoy una duda nueva no me asusta; la trato como invitada, RLR",
  "Gracias por las preguntas sin respuesta; me mantienen vivo y curioso, RLR",
  "Hoy convivo con un misterio sin querer resolverlo a la fuerza, RLR",
  "Doy las gracias por las personas que me amaron y por las que no supieron, RLR",
  "Hoy comprendo que cada quien quiere desde donde puede, RLR",
  "Gracias por mi capacidad de seguir aprendiendo a amar, RLR",
  "Hoy amo un poquito mejor que ayer, sin esperar reconocimiento, RLR",
  "Doy las gracias por mi mente, mi cuerpo, mi corazón, mi alma; todos al servicio de la vida, RLR",
  "Hoy me siento parte de algo más grande que entiendo a medias, RLR",
  "Gracias por la fe pequeña que sigue ahí, terca, después de todo, RLR",
  "Hoy sostengo mi fe, sin necesidad de que sea de ningún color, RLR",
  "Doy las gracias por mis ancestros, conocidos y desconocidos; estoy parado sobre sus pies, RLR",
  "Hoy honro a alguien de mi linaje con un acto consciente, RLR",
  "Gracias por los desconocidos que me sostuvieron en mil maneras invisibles, RLR",
  "Hoy mando un buen pensamiento al mundo, sin destinatario, RLR",
  "Doy las gracias por estar vivo en este preciso momento de la historia, RLR",
  "Mi presencia aquí, aunque sea breve, importa, RLR",
  "Hoy dejo el mundo un poquito mejor de cómo lo encontré, en algo, en algún lado, aunque sea pequeño, RLR",
  "Gracias, gracias, gracias: por todo, sin condiciones, sin reservas, sin pero, sin todavía, RLR"
];

// Punto de referencia fijo: index 0 en este instante exacto. México dejó de
// usar horario de verano en 2022 (CDMX se queda todo el año en UTC-6), así
// que 3:33pm CDMX es siempre 21:33 UTC — no hace falta ninguna librería de
// zonas horarias ni manejar cambios de horario.
const REFERENCE_UTC_MS = Date.UTC(2026, 0, 1, 21, 33, 0);
const DAY_MS = 24 * 60 * 60 * 1000;

export function getDailyPhraseIndex(nowMs: number = Date.now()): number {
  const daysElapsed = Math.floor((nowMs - REFERENCE_UTC_MS) / DAY_MS);
  return ((daysElapsed % PHRASES.length) + PHRASES.length) % PHRASES.length;
}

// La misma frase para todos, todo el día, hasta que cambia a la siguiente a
// las 3:33pm hora CDMX — al llegar al final de la lista, vuelve a empezar en
// loop infinito.
export function getDailyPhrase(nowMs: number = Date.now()): string {
  return PHRASES[getDailyPhraseIndex(nowMs)];
}
